define({
  "_widgetLabel": "試_Visibility____驗",
  "observerLocation": "試_Observer Location______驗",
  "fieldOfView": "試_Field of View_____驗",
  "useMilsText": "試_Use mils for bearing angles_________驗",
  "observerHeight": "試_Observer Height______驗",
  "minObsDistance": "試_Min Observable Distance________驗",
  "maxObsDistance": "試_Max Observable Distance________驗",
  "taskURLError": "試_The widget configuration file contains a URL that is unreachable. Please check with your system administrator__________________________________驗",
  "taskURLInvalid": "試_The geoprocessing task configured with this widget is not valid. Please check with your system administrator_________________________________驗",
  "viewshedError": "試_An error occured whilst creating visibility. Please ensure your observer location falls within the extent of your elevation surface.</p>__________________________________________驗",
  "validationError": "試_<p>The visibility creation form has missing or invalid parameters, Please ensure:</p><ul><li>An observer location has been set.</li><li>The observer Field of View is not 0.</li><li>The observer height contains a valid value.</li><li>The min and max observable distances contain valid values.</li></ul>___________________________________________________________________________________________驗",
  "comfirmInputNotation": "試_Confirm Input Notation________驗",
  "notationsMatch": "試_notations match your input please confirm which you would like to use______________________驗:",
  "createBtn": "試_Create___驗",
  "clearBtn": "試_Clear___驗",
  "setCoordFormat": "試_Set Coordinate Format String_________驗",
  "prefixNumbers": "試_Add '+/-' prefix to positive and negative numbers________________驗",
  "parseCoordinatesError": "試_Unable to parse coordinates. Please check your input_________________驗.",
  "cancelBtn": "試_Cancel___驗",
  "applyBtn": "試_Apply___驗",
  "DD": "試_DD__驗",
  "DDM": "試_DDM__驗",
  "DMS": "試_DMS__驗",
  "DDRev": "試_DDRev___驗",
  "DDMRev": "試_DDMRev___驗",
  "DMSRev": "試_DMSRev___驗",
  "USNG": "試_USNG__驗",
  "MGRS": "試_MGRS__驗",
  "UTM_H": "試_UTM (H)___驗",
  "UTM": "試_UTM__驗",
  "GARS": "試_GARS__驗",
  "GEOREF": "試_GEOREF___驗",
  "DDLatLongNotation": "試_Decimal Degrees - Latitude/Longitude____________驗",
  "DDLongLatNotation": "試_Decimal Degrees  - Longitude/Latitude____________驗",
  "DDMLatLongNotation": "試_Degrees Decimal Minutes - Latitude/Longitude______________驗",
  "DDMLongLatNotation": "試_Degrees Decimal Minutes - Longitude/Latitude______________驗",
  "DMSLatLongNotation": "試_Degrees Minutes Seconds - Latitude/Longitude______________驗",
  "DMSLongLatNotation": "試_Degrees Minutes Seconds - Longitude/Latitude______________驗",
  "GARSNotation": "試_GARS__驗",
  "GEOREFNotation": "試_GEOREF___驗",
  "MGRSNotation": "試_MGRS__驗",
  "USNGNotation": "試_USNG__驗",
  "UTMBandNotation": "試_UTM - Band Letter______驗",
  "UTMHemNotation": "試_UTM - Hemisphere (N/S)________驗"
});