define({
  "_widgetLabel": "Å_Visibility____ö",
  "observerLocation": "Å_Observer Location______ö",
  "fieldOfView": "Å_Field of View_____ö",
  "useMilsText": "Å_Use mils for bearing angles_________ö",
  "observerHeight": "Å_Observer Height______ö",
  "minObsDistance": "Å_Min Observable Distance________ö",
  "maxObsDistance": "Å_Max Observable Distance________ö",
  "taskURLError": "Å_The widget configuration file contains a URL that is unreachable. Please check with your system administrator__________________________________ö",
  "taskURLInvalid": "Å_The geoprocessing task configured with this widget is not valid. Please check with your system administrator_________________________________ö",
  "viewshedError": "Å_An error occured whilst creating visibility. Please ensure your observer location falls within the extent of your elevation surface.</p>__________________________________________ö",
  "validationError": "Å_<p>The visibility creation form has missing or invalid parameters, Please ensure:</p><ul><li>An observer location has been set.</li><li>The observer Field of View is not 0.</li><li>The observer height contains a valid value.</li><li>The min and max observable distances contain valid values.</li></ul>___________________________________________________________________________________________ö",
  "comfirmInputNotation": "Å_Confirm Input Notation________ö",
  "notationsMatch": "Å_notations match your input please confirm which you would like to use______________________ö:",
  "createBtn": "Å_Create___ö",
  "clearBtn": "Å_Clear___ö",
  "setCoordFormat": "Å_Set Coordinate Format String_________ö",
  "prefixNumbers": "Å_Add '+/-' prefix to positive and negative numbers________________ö",
  "parseCoordinatesError": "Å_Unable to parse coordinates. Please check your input_________________ö.",
  "cancelBtn": "Å_Cancel___ö",
  "applyBtn": "Å_Apply___ö",
  "DD": "Å_DD__ö",
  "DDM": "Å_DDM__ö",
  "DMS": "Å_DMS__ö",
  "DDRev": "Å_DDRev___ö",
  "DDMRev": "Å_DDMRev___ö",
  "DMSRev": "Å_DMSRev___ö",
  "USNG": "Å_USNG__ö",
  "MGRS": "Å_MGRS__ö",
  "UTM_H": "Å_UTM (H)___ö",
  "UTM": "Å_UTM__ö",
  "GARS": "Å_GARS__ö",
  "GEOREF": "Å_GEOREF___ö",
  "DDLatLongNotation": "Å_Decimal Degrees - Latitude/Longitude____________ö",
  "DDLongLatNotation": "Å_Decimal Degrees  - Longitude/Latitude____________ö",
  "DDMLatLongNotation": "Å_Degrees Decimal Minutes - Latitude/Longitude______________ö",
  "DDMLongLatNotation": "Å_Degrees Decimal Minutes - Longitude/Latitude______________ö",
  "DMSLatLongNotation": "Å_Degrees Minutes Seconds - Latitude/Longitude______________ö",
  "DMSLongLatNotation": "Å_Degrees Minutes Seconds - Longitude/Latitude______________ö",
  "GARSNotation": "Å_GARS__ö",
  "GEOREFNotation": "Å_GEOREF___ö",
  "MGRSNotation": "Å_MGRS__ö",
  "USNGNotation": "Å_USNG__ö",
  "UTMBandNotation": "Å_UTM - Band Letter______ö",
  "UTMHemNotation": "Å_UTM - Hemisphere (N/S)________ö"
});