define({
  "_widgetLabel": "ı_Visibility____İ",
  "observerLocation": "ı_Observer Location______İ",
  "fieldOfView": "ı_Field of View_____İ",
  "useMilsText": "ı_Use mils for bearing angles_________İ",
  "observerHeight": "ı_Observer Height______İ",
  "minObsDistance": "ı_Min Observable Distance________İ",
  "maxObsDistance": "ı_Max Observable Distance________İ",
  "taskURLError": "ı_The widget configuration file contains a URL that is unreachable. Please check with your system administrator__________________________________İ",
  "taskURLInvalid": "ı_The geoprocessing task configured with this widget is not valid. Please check with your system administrator_________________________________İ",
  "viewshedError": "ı_An error occured whilst creating visibility. Please ensure your observer location falls within the extent of your elevation surface.</p>__________________________________________İ",
  "validationError": "ı_<p>The visibility creation form has missing or invalid parameters, Please ensure:</p><ul><li>An observer location has been set.</li><li>The observer Field of View is not 0.</li><li>The observer height contains a valid value.</li><li>The min and max observable distances contain valid values.</li></ul>___________________________________________________________________________________________İ",
  "comfirmInputNotation": "ı_Confirm Input Notation________İ",
  "notationsMatch": "ı_notations match your input please confirm which you would like to use______________________İ:",
  "createBtn": "ı_Create___İ",
  "clearBtn": "ı_Clear___İ",
  "setCoordFormat": "ı_Set Coordinate Format String_________İ",
  "prefixNumbers": "ı_Add '+/-' prefix to positive and negative numbers________________İ",
  "parseCoordinatesError": "ı_Unable to parse coordinates. Please check your input_________________İ.",
  "cancelBtn": "ı_Cancel___İ",
  "applyBtn": "ı_Apply___İ",
  "DD": "ı_DD__İ",
  "DDM": "ı_DDM__İ",
  "DMS": "ı_DMS__İ",
  "DDRev": "ı_DDRev___İ",
  "DDMRev": "ı_DDMRev___İ",
  "DMSRev": "ı_DMSRev___İ",
  "USNG": "ı_USNG__İ",
  "MGRS": "ı_MGRS__İ",
  "UTM_H": "ı_UTM (H)___İ",
  "UTM": "ı_UTM__İ",
  "GARS": "ı_GARS__İ",
  "GEOREF": "ı_GEOREF___İ",
  "DDLatLongNotation": "ı_Decimal Degrees - Latitude/Longitude____________İ",
  "DDLongLatNotation": "ı_Decimal Degrees  - Longitude/Latitude____________İ",
  "DDMLatLongNotation": "ı_Degrees Decimal Minutes - Latitude/Longitude______________İ",
  "DDMLongLatNotation": "ı_Degrees Decimal Minutes - Longitude/Latitude______________İ",
  "DMSLatLongNotation": "ı_Degrees Minutes Seconds - Latitude/Longitude______________İ",
  "DMSLongLatNotation": "ı_Degrees Minutes Seconds - Longitude/Latitude______________İ",
  "GARSNotation": "ı_GARS__İ",
  "GEOREFNotation": "ı_GEOREF___İ",
  "MGRSNotation": "ı_MGRS__İ",
  "USNGNotation": "ı_USNG__İ",
  "UTMBandNotation": "ı_UTM - Band Letter______İ",
  "UTMHemNotation": "ı_UTM - Hemisphere (N/S)________İ"
});