define({
  "_widgetLabel": "Ř_Visibility____ů",
  "observerLocation": "Ř_Observer Location______ů",
  "fieldOfView": "Ř_Field of View_____ů",
  "useMilsText": "Ř_Use mils for bearing angles_________ů",
  "observerHeight": "Ř_Observer Height______ů",
  "minObsDistance": "Ř_Min Observable Distance________ů",
  "maxObsDistance": "Ř_Max Observable Distance________ů",
  "taskURLError": "Ř_The widget configuration file contains a URL that is unreachable. Please check with your system administrator__________________________________ů",
  "taskURLInvalid": "Ř_The geoprocessing task configured with this widget is not valid. Please check with your system administrator_________________________________ů",
  "viewshedError": "Ř_An error occured whilst creating visibility. Please ensure your observer location falls within the extent of your elevation surface.</p>__________________________________________ů",
  "validationError": "Ř_<p>The visibility creation form has missing or invalid parameters, Please ensure:</p><ul><li>An observer location has been set.</li><li>The observer Field of View is not 0.</li><li>The observer height contains a valid value.</li><li>The min and max observable distances contain valid values.</li></ul>___________________________________________________________________________________________ů",
  "comfirmInputNotation": "Ř_Confirm Input Notation________ů",
  "notationsMatch": "Ř_notations match your input please confirm which you would like to use______________________ů:",
  "createBtn": "Ř_Create___ů",
  "clearBtn": "Ř_Clear___ů",
  "setCoordFormat": "Ř_Set Coordinate Format String_________ů",
  "prefixNumbers": "Ř_Add '+/-' prefix to positive and negative numbers________________ů",
  "parseCoordinatesError": "Ř_Unable to parse coordinates. Please check your input_________________ů.",
  "cancelBtn": "Ř_Cancel___ů",
  "applyBtn": "Ř_Apply___ů",
  "DD": "Ř_DD__ů",
  "DDM": "Ř_DDM__ů",
  "DMS": "Ř_DMS__ů",
  "DDRev": "Ř_DDRev___ů",
  "DDMRev": "Ř_DDMRev___ů",
  "DMSRev": "Ř_DMSRev___ů",
  "USNG": "Ř_USNG__ů",
  "MGRS": "Ř_MGRS__ů",
  "UTM_H": "Ř_UTM (H)___ů",
  "UTM": "Ř_UTM__ů",
  "GARS": "Ř_GARS__ů",
  "GEOREF": "Ř_GEOREF___ů",
  "DDLatLongNotation": "Ř_Decimal Degrees - Latitude/Longitude____________ů",
  "DDLongLatNotation": "Ř_Decimal Degrees  - Longitude/Latitude____________ů",
  "DDMLatLongNotation": "Ř_Degrees Decimal Minutes - Latitude/Longitude______________ů",
  "DDMLongLatNotation": "Ř_Degrees Decimal Minutes - Longitude/Latitude______________ů",
  "DMSLatLongNotation": "Ř_Degrees Minutes Seconds - Latitude/Longitude______________ů",
  "DMSLongLatNotation": "Ř_Degrees Minutes Seconds - Longitude/Latitude______________ů",
  "GARSNotation": "Ř_GARS__ů",
  "GEOREFNotation": "Ř_GEOREF___ů",
  "MGRSNotation": "Ř_MGRS__ů",
  "USNGNotation": "Ř_USNG__ů",
  "UTMBandNotation": "Ř_UTM - Band Letter______ů",
  "UTMHemNotation": "Ř_UTM - Hemisphere (N/S)________ů"
});