define({
  "_widgetLabel": "כן_Visibility____ש",
  "observerLocation": "כן_Observer Location______ש",
  "fieldOfView": "כן_Field of View_____ש",
  "useMilsText": "כן_Use mils for bearing angles_________ש",
  "observerHeight": "כן_Observer Height______ש",
  "minObsDistance": "כן_Min Observable Distance________ש",
  "maxObsDistance": "כן_Max Observable Distance________ש",
  "taskURLError": "כן_The widget configuration file contains a URL that is unreachable. Please check with your system administrator__________________________________ש",
  "taskURLInvalid": "כן_The geoprocessing task configured with this widget is not valid. Please check with your system administrator_________________________________ש",
  "viewshedError": "כן_An error occured whilst creating visibility. Please ensure your observer location falls within the extent of your elevation surface.</p>__________________________________________ש",
  "validationError": "כן_<p>The visibility creation form has missing or invalid parameters, Please ensure:</p><ul><li>An observer location has been set.</li><li>The observer Field of View is not 0.</li><li>The observer height contains a valid value.</li><li>The min and max observable distances contain valid values.</li></ul>___________________________________________________________________________________________ש",
  "comfirmInputNotation": "כן_Confirm Input Notation________ש",
  "notationsMatch": "כן_notations match your input please confirm which you would like to use______________________ש:",
  "createBtn": "כן_Create___ש",
  "clearBtn": "כן_Clear___ש",
  "setCoordFormat": "כן_Set Coordinate Format String_________ש",
  "prefixNumbers": "כן_Add '+/-' prefix to positive and negative numbers________________ש",
  "parseCoordinatesError": "כן_Unable to parse coordinates. Please check your input_________________ש.",
  "cancelBtn": "כן_Cancel___ש",
  "applyBtn": "כן_Apply___ש",
  "DD": "כן_DD__ש",
  "DDM": "כן_DDM__ש",
  "DMS": "כן_DMS__ש",
  "DDRev": "כן_DDRev___ש",
  "DDMRev": "כן_DDMRev___ש",
  "DMSRev": "כן_DMSRev___ש",
  "USNG": "כן_USNG__ש",
  "MGRS": "כן_MGRS__ש",
  "UTM_H": "כן_UTM (H)___ש",
  "UTM": "כן_UTM__ש",
  "GARS": "כן_GARS__ש",
  "GEOREF": "כן_GEOREF___ש",
  "DDLatLongNotation": "כן_Decimal Degrees - Latitude/Longitude____________ש",
  "DDLongLatNotation": "כן_Decimal Degrees  - Longitude/Latitude____________ש",
  "DDMLatLongNotation": "כן_Degrees Decimal Minutes - Latitude/Longitude______________ש",
  "DDMLongLatNotation": "כן_Degrees Decimal Minutes - Longitude/Latitude______________ש",
  "DMSLatLongNotation": "כן_Degrees Minutes Seconds - Latitude/Longitude______________ש",
  "DMSLongLatNotation": "כן_Degrees Minutes Seconds - Longitude/Latitude______________ש",
  "GARSNotation": "כן_GARS__ש",
  "GEOREFNotation": "כן_GEOREF___ש",
  "MGRSNotation": "כן_MGRS__ש",
  "USNGNotation": "כן_USNG__ש",
  "UTMBandNotation": "כן_UTM - Band Letter______ש",
  "UTMHemNotation": "כן_UTM - Hemisphere (N/S)________ש"
});