define({
  "_widgetLabel": "한_Visibility____빠",
  "observerLocation": "한_Observer Location______빠",
  "fieldOfView": "한_Field of View_____빠",
  "useMilsText": "한_Use mils for bearing angles_________빠",
  "observerHeight": "한_Observer Height______빠",
  "minObsDistance": "한_Min Observable Distance________빠",
  "maxObsDistance": "한_Max Observable Distance________빠",
  "taskURLError": "한_The widget configuration file contains a URL that is unreachable. Please check with your system administrator__________________________________빠",
  "taskURLInvalid": "한_The geoprocessing task configured with this widget is not valid. Please check with your system administrator_________________________________빠",
  "viewshedError": "한_An error occured whilst creating visibility. Please ensure your observer location falls within the extent of your elevation surface.</p>__________________________________________빠",
  "validationError": "한_<p>The visibility creation form has missing or invalid parameters, Please ensure:</p><ul><li>An observer location has been set.</li><li>The observer Field of View is not 0.</li><li>The observer height contains a valid value.</li><li>The min and max observable distances contain valid values.</li></ul>___________________________________________________________________________________________빠",
  "comfirmInputNotation": "한_Confirm Input Notation________빠",
  "notationsMatch": "한_notations match your input please confirm which you would like to use______________________빠:",
  "createBtn": "한_Create___빠",
  "clearBtn": "한_Clear___빠",
  "setCoordFormat": "한_Set Coordinate Format String_________빠",
  "prefixNumbers": "한_Add '+/-' prefix to positive and negative numbers________________빠",
  "parseCoordinatesError": "한_Unable to parse coordinates. Please check your input_________________빠.",
  "cancelBtn": "한_Cancel___빠",
  "applyBtn": "한_Apply___빠",
  "DD": "한_DD__빠",
  "DDM": "한_DDM__빠",
  "DMS": "한_DMS__빠",
  "DDRev": "한_DDRev___빠",
  "DDMRev": "한_DDMRev___빠",
  "DMSRev": "한_DMSRev___빠",
  "USNG": "한_USNG__빠",
  "MGRS": "한_MGRS__빠",
  "UTM_H": "한_UTM (H)___빠",
  "UTM": "한_UTM__빠",
  "GARS": "한_GARS__빠",
  "GEOREF": "한_GEOREF___빠",
  "DDLatLongNotation": "한_Decimal Degrees - Latitude/Longitude____________빠",
  "DDLongLatNotation": "한_Decimal Degrees  - Longitude/Latitude____________빠",
  "DDMLatLongNotation": "한_Degrees Decimal Minutes - Latitude/Longitude______________빠",
  "DDMLongLatNotation": "한_Degrees Decimal Minutes - Longitude/Latitude______________빠",
  "DMSLatLongNotation": "한_Degrees Minutes Seconds - Latitude/Longitude______________빠",
  "DMSLongLatNotation": "한_Degrees Minutes Seconds - Longitude/Latitude______________빠",
  "GARSNotation": "한_GARS__빠",
  "GEOREFNotation": "한_GEOREF___빠",
  "MGRSNotation": "한_MGRS__빠",
  "USNGNotation": "한_USNG__빠",
  "UTMBandNotation": "한_UTM - Band Letter______빠",
  "UTMHemNotation": "한_UTM - Hemisphere (N/S)________빠"
});