define({
  "_widgetLabel": "Ж_Visibility____Я",
  "observerLocation": "Ж_Observer Location______Я",
  "fieldOfView": "Ж_Field of View_____Я",
  "useMilsText": "Ж_Use mils for bearing angles_________Я",
  "observerHeight": "Ж_Observer Height______Я",
  "minObsDistance": "Ж_Min Observable Distance________Я",
  "maxObsDistance": "Ж_Max Observable Distance________Я",
  "taskURLError": "Ж_The widget configuration file contains a URL that is unreachable. Please check with your system administrator__________________________________Я",
  "taskURLInvalid": "Ж_The geoprocessing task configured with this widget is not valid. Please check with your system administrator_________________________________Я",
  "viewshedError": "Ж_An error occured whilst creating visibility. Please ensure your observer location falls within the extent of your elevation surface.</p>__________________________________________Я",
  "validationError": "Ж_<p>The visibility creation form has missing or invalid parameters, Please ensure:</p><ul><li>An observer location has been set.</li><li>The observer Field of View is not 0.</li><li>The observer height contains a valid value.</li><li>The min and max observable distances contain valid values.</li></ul>___________________________________________________________________________________________Я",
  "comfirmInputNotation": "Ж_Confirm Input Notation________Я",
  "notationsMatch": "Ж_notations match your input please confirm which you would like to use______________________Я:",
  "createBtn": "Ж_Create___Я",
  "clearBtn": "Ж_Clear___Я",
  "setCoordFormat": "Ж_Set Coordinate Format String_________Я",
  "prefixNumbers": "Ж_Add '+/-' prefix to positive and negative numbers________________Я",
  "parseCoordinatesError": "Ж_Unable to parse coordinates. Please check your input_________________Я.",
  "cancelBtn": "Ж_Cancel___Я",
  "applyBtn": "Ж_Apply___Я",
  "DD": "Ж_DD__Я",
  "DDM": "Ж_DDM__Я",
  "DMS": "Ж_DMS__Я",
  "DDRev": "Ж_DDRev___Я",
  "DDMRev": "Ж_DDMRev___Я",
  "DMSRev": "Ж_DMSRev___Я",
  "USNG": "Ж_USNG__Я",
  "MGRS": "Ж_MGRS__Я",
  "UTM_H": "Ж_UTM (H)___Я",
  "UTM": "Ж_UTM__Я",
  "GARS": "Ж_GARS__Я",
  "GEOREF": "Ж_GEOREF___Я",
  "DDLatLongNotation": "Ж_Decimal Degrees - Latitude/Longitude____________Я",
  "DDLongLatNotation": "Ж_Decimal Degrees  - Longitude/Latitude____________Я",
  "DDMLatLongNotation": "Ж_Degrees Decimal Minutes - Latitude/Longitude______________Я",
  "DDMLongLatNotation": "Ж_Degrees Decimal Minutes - Longitude/Latitude______________Я",
  "DMSLatLongNotation": "Ж_Degrees Minutes Seconds - Latitude/Longitude______________Я",
  "DMSLongLatNotation": "Ж_Degrees Minutes Seconds - Longitude/Latitude______________Я",
  "GARSNotation": "Ж_GARS__Я",
  "GEOREFNotation": "Ж_GEOREF___Я",
  "MGRSNotation": "Ж_MGRS__Я",
  "USNGNotation": "Ж_USNG__Я",
  "UTMBandNotation": "Ж_UTM - Band Letter______Я",
  "UTMHemNotation": "Ж_UTM - Hemisphere (N/S)________Я"
});