define({
  "_widgetLabel": "ø_Visibility____å",
  "observerLocation": "ø_Observer Location______å",
  "fieldOfView": "ø_Field of View_____å",
  "useMilsText": "ø_Use mils for bearing angles_________å",
  "observerHeight": "ø_Observer Height______å",
  "minObsDistance": "ø_Min Observable Distance________å",
  "maxObsDistance": "ø_Max Observable Distance________å",
  "taskURLError": "ø_The widget configuration file contains a URL that is unreachable. Please check with your system administrator__________________________________å",
  "taskURLInvalid": "ø_The geoprocessing task configured with this widget is not valid. Please check with your system administrator_________________________________å",
  "viewshedError": "ø_An error occured whilst creating visibility. Please ensure your observer location falls within the extent of your elevation surface.</p>__________________________________________å",
  "validationError": "ø_<p>The visibility creation form has missing or invalid parameters, Please ensure:</p><ul><li>An observer location has been set.</li><li>The observer Field of View is not 0.</li><li>The observer height contains a valid value.</li><li>The min and max observable distances contain valid values.</li></ul>___________________________________________________________________________________________å",
  "comfirmInputNotation": "ø_Confirm Input Notation________å",
  "notationsMatch": "ø_notations match your input please confirm which you would like to use______________________å:",
  "createBtn": "ø_Create___å",
  "clearBtn": "ø_Clear___å",
  "setCoordFormat": "ø_Set Coordinate Format String_________å",
  "prefixNumbers": "ø_Add '+/-' prefix to positive and negative numbers________________å",
  "parseCoordinatesError": "ø_Unable to parse coordinates. Please check your input_________________å.",
  "cancelBtn": "ø_Cancel___å",
  "applyBtn": "ø_Apply___å",
  "DD": "ø_DD__å",
  "DDM": "ø_DDM__å",
  "DMS": "ø_DMS__å",
  "DDRev": "ø_DDRev___å",
  "DDMRev": "ø_DDMRev___å",
  "DMSRev": "ø_DMSRev___å",
  "USNG": "ø_USNG__å",
  "MGRS": "ø_MGRS__å",
  "UTM_H": "ø_UTM (H)___å",
  "UTM": "ø_UTM__å",
  "GARS": "ø_GARS__å",
  "GEOREF": "ø_GEOREF___å",
  "DDLatLongNotation": "ø_Decimal Degrees - Latitude/Longitude____________å",
  "DDLongLatNotation": "ø_Decimal Degrees  - Longitude/Latitude____________å",
  "DDMLatLongNotation": "ø_Degrees Decimal Minutes - Latitude/Longitude______________å",
  "DDMLongLatNotation": "ø_Degrees Decimal Minutes - Longitude/Latitude______________å",
  "DMSLatLongNotation": "ø_Degrees Minutes Seconds - Latitude/Longitude______________å",
  "DMSLongLatNotation": "ø_Degrees Minutes Seconds - Longitude/Latitude______________å",
  "GARSNotation": "ø_GARS__å",
  "GEOREFNotation": "ø_GEOREF___å",
  "MGRSNotation": "ø_MGRS__å",
  "USNGNotation": "ø_USNG__å",
  "UTMBandNotation": "ø_UTM - Band Letter______å",
  "UTMHemNotation": "ø_UTM - Hemisphere (N/S)________å"
});