define({
  "_widgetLabel": "आ_Visibility____ज",
  "observerLocation": "आ_Observer Location______ज",
  "fieldOfView": "आ_Field of View_____ज",
  "useMilsText": "आ_Use mils for bearing angles_________ज",
  "observerHeight": "आ_Observer Height______ज",
  "minObsDistance": "आ_Min Observable Distance________ज",
  "maxObsDistance": "आ_Max Observable Distance________ज",
  "taskURLError": "आ_The widget configuration file contains a URL that is unreachable. Please check with your system administrator__________________________________ज",
  "taskURLInvalid": "आ_The geoprocessing task configured with this widget is not valid. Please check with your system administrator_________________________________ज",
  "viewshedError": "आ_An error occured whilst creating visibility. Please ensure your observer location falls within the extent of your elevation surface.</p>__________________________________________ज",
  "validationError": "आ_<p>The visibility creation form has missing or invalid parameters, Please ensure:</p><ul><li>An observer location has been set.</li><li>The observer Field of View is not 0.</li><li>The observer height contains a valid value.</li><li>The min and max observable distances contain valid values.</li></ul>___________________________________________________________________________________________ज",
  "comfirmInputNotation": "आ_Confirm Input Notation________ज",
  "notationsMatch": "आ_notations match your input please confirm which you would like to use______________________ज:",
  "createBtn": "आ_Create___ज",
  "clearBtn": "आ_Clear___ज",
  "setCoordFormat": "आ_Set Coordinate Format String_________ज",
  "prefixNumbers": "आ_Add '+/-' prefix to positive and negative numbers________________ज",
  "parseCoordinatesError": "आ_Unable to parse coordinates. Please check your input_________________ज.",
  "cancelBtn": "आ_Cancel___ज",
  "applyBtn": "आ_Apply___ज",
  "DD": "आ_DD__ज",
  "DDM": "आ_DDM__ज",
  "DMS": "आ_DMS__ज",
  "DDRev": "आ_DDRev___ज",
  "DDMRev": "आ_DDMRev___ज",
  "DMSRev": "आ_DMSRev___ज",
  "USNG": "आ_USNG__ज",
  "MGRS": "आ_MGRS__ज",
  "UTM_H": "आ_UTM (H)___ज",
  "UTM": "आ_UTM__ज",
  "GARS": "आ_GARS__ज",
  "GEOREF": "आ_GEOREF___ज",
  "DDLatLongNotation": "आ_Decimal Degrees - Latitude/Longitude____________ज",
  "DDLongLatNotation": "आ_Decimal Degrees  - Longitude/Latitude____________ज",
  "DDMLatLongNotation": "आ_Degrees Decimal Minutes - Latitude/Longitude______________ज",
  "DDMLongLatNotation": "आ_Degrees Decimal Minutes - Longitude/Latitude______________ज",
  "DMSLatLongNotation": "आ_Degrees Minutes Seconds - Latitude/Longitude______________ज",
  "DMSLongLatNotation": "आ_Degrees Minutes Seconds - Longitude/Latitude______________ज",
  "GARSNotation": "आ_GARS__ज",
  "GEOREFNotation": "आ_GEOREF___ज",
  "MGRSNotation": "आ_MGRS__ज",
  "USNGNotation": "आ_USNG__ज",
  "UTMBandNotation": "आ_UTM - Band Letter______ज",
  "UTMHemNotation": "आ_UTM - Hemisphere (N/S)________ज"
});