define({
  "_widgetLabel": "Š_Visibility____ä",
  "observerLocation": "Š_Observer Location______ä",
  "fieldOfView": "Š_Field of View_____ä",
  "useMilsText": "Š_Use mils for bearing angles_________ä",
  "observerHeight": "Š_Observer Height______ä",
  "minObsDistance": "Š_Min Observable Distance________ä",
  "maxObsDistance": "Š_Max Observable Distance________ä",
  "taskURLError": "Š_The widget configuration file contains a URL that is unreachable. Please check with your system administrator__________________________________ä",
  "taskURLInvalid": "Š_The geoprocessing task configured with this widget is not valid. Please check with your system administrator_________________________________ä",
  "viewshedError": "Š_An error occured whilst creating visibility. Please ensure your observer location falls within the extent of your elevation surface.</p>__________________________________________ä",
  "validationError": "Š_<p>The visibility creation form has missing or invalid parameters, Please ensure:</p><ul><li>An observer location has been set.</li><li>The observer Field of View is not 0.</li><li>The observer height contains a valid value.</li><li>The min and max observable distances contain valid values.</li></ul>___________________________________________________________________________________________ä",
  "comfirmInputNotation": "Š_Confirm Input Notation________ä",
  "notationsMatch": "Š_notations match your input please confirm which you would like to use______________________ä:",
  "createBtn": "Š_Create___ä",
  "clearBtn": "Š_Clear___ä",
  "setCoordFormat": "Š_Set Coordinate Format String_________ä",
  "prefixNumbers": "Š_Add '+/-' prefix to positive and negative numbers________________ä",
  "parseCoordinatesError": "Š_Unable to parse coordinates. Please check your input_________________ä.",
  "cancelBtn": "Š_Cancel___ä",
  "applyBtn": "Š_Apply___ä",
  "DD": "Š_DD__ä",
  "DDM": "Š_DDM__ä",
  "DMS": "Š_DMS__ä",
  "DDRev": "Š_DDRev___ä",
  "DDMRev": "Š_DDMRev___ä",
  "DMSRev": "Š_DMSRev___ä",
  "USNG": "Š_USNG__ä",
  "MGRS": "Š_MGRS__ä",
  "UTM_H": "Š_UTM (H)___ä",
  "UTM": "Š_UTM__ä",
  "GARS": "Š_GARS__ä",
  "GEOREF": "Š_GEOREF___ä",
  "DDLatLongNotation": "Š_Decimal Degrees - Latitude/Longitude____________ä",
  "DDLongLatNotation": "Š_Decimal Degrees  - Longitude/Latitude____________ä",
  "DDMLatLongNotation": "Š_Degrees Decimal Minutes - Latitude/Longitude______________ä",
  "DDMLongLatNotation": "Š_Degrees Decimal Minutes - Longitude/Latitude______________ä",
  "DMSLatLongNotation": "Š_Degrees Minutes Seconds - Latitude/Longitude______________ä",
  "DMSLongLatNotation": "Š_Degrees Minutes Seconds - Longitude/Latitude______________ä",
  "GARSNotation": "Š_GARS__ä",
  "GEOREFNotation": "Š_GEOREF___ä",
  "MGRSNotation": "Š_MGRS__ä",
  "USNGNotation": "Š_USNG__ä",
  "UTMBandNotation": "Š_UTM - Band Letter______ä",
  "UTMHemNotation": "Š_UTM - Hemisphere (N/S)________ä"
});