define({
  "_widgetLabel": "Š_Visibility____č",
  "observerLocation": "Š_Observer Location______č",
  "fieldOfView": "Š_Field of View_____č",
  "useMilsText": "Š_Use mils for bearing angles_________č",
  "observerHeight": "Š_Observer Height______č",
  "minObsDistance": "Š_Min Observable Distance________č",
  "maxObsDistance": "Š_Max Observable Distance________č",
  "taskURLError": "Š_The widget configuration file contains a URL that is unreachable. Please check with your system administrator__________________________________č",
  "taskURLInvalid": "Š_The geoprocessing task configured with this widget is not valid. Please check with your system administrator_________________________________č",
  "viewshedError": "Š_An error occured whilst creating visibility. Please ensure your observer location falls within the extent of your elevation surface.</p>__________________________________________č",
  "validationError": "Š_<p>The visibility creation form has missing or invalid parameters, Please ensure:</p><ul><li>An observer location has been set.</li><li>The observer Field of View is not 0.</li><li>The observer height contains a valid value.</li><li>The min and max observable distances contain valid values.</li></ul>___________________________________________________________________________________________č",
  "comfirmInputNotation": "Š_Confirm Input Notation________č",
  "notationsMatch": "Š_notations match your input please confirm which you would like to use______________________č:",
  "createBtn": "Š_Create___č",
  "clearBtn": "Š_Clear___č",
  "setCoordFormat": "Š_Set Coordinate Format String_________č",
  "prefixNumbers": "Š_Add '+/-' prefix to positive and negative numbers________________č",
  "parseCoordinatesError": "Š_Unable to parse coordinates. Please check your input_________________č.",
  "cancelBtn": "Š_Cancel___č",
  "applyBtn": "Š_Apply___č",
  "DD": "Š_DD__č",
  "DDM": "Š_DDM__č",
  "DMS": "Š_DMS__č",
  "DDRev": "Š_DDRev___č",
  "DDMRev": "Š_DDMRev___č",
  "DMSRev": "Š_DMSRev___č",
  "USNG": "Š_USNG__č",
  "MGRS": "Š_MGRS__č",
  "UTM_H": "Š_UTM (H)___č",
  "UTM": "Š_UTM__č",
  "GARS": "Š_GARS__č",
  "GEOREF": "Š_GEOREF___č",
  "DDLatLongNotation": "Š_Decimal Degrees - Latitude/Longitude____________č",
  "DDLongLatNotation": "Š_Decimal Degrees  - Longitude/Latitude____________č",
  "DDMLatLongNotation": "Š_Degrees Decimal Minutes - Latitude/Longitude______________č",
  "DDMLongLatNotation": "Š_Degrees Decimal Minutes - Longitude/Latitude______________č",
  "DMSLatLongNotation": "Š_Degrees Minutes Seconds - Latitude/Longitude______________č",
  "DMSLongLatNotation": "Š_Degrees Minutes Seconds - Longitude/Latitude______________č",
  "GARSNotation": "Š_GARS__č",
  "GEOREFNotation": "Š_GEOREF___č",
  "MGRSNotation": "Š_MGRS__č",
  "USNGNotation": "Š_USNG__č",
  "UTMBandNotation": "Š_UTM - Band Letter______č",
  "UTMHemNotation": "Š_UTM - Hemisphere (N/S)________č"
});