define({
  "_widgetLabel": "ng_Visibility____ny",
  "observerLocation": "ng_Observer Location______ny",
  "fieldOfView": "ng_Field of View_____ny",
  "useMilsText": "ng_Use mils for bearing angles_________ny",
  "observerHeight": "ng_Observer Height______ny",
  "minObsDistance": "ng_Min Observable Distance________ny",
  "maxObsDistance": "ng_Max Observable Distance________ny",
  "taskURLError": "ng_The widget configuration file contains a URL that is unreachable. Please check with your system administrator__________________________________ny",
  "taskURLInvalid": "ng_The geoprocessing task configured with this widget is not valid. Please check with your system administrator_________________________________ny",
  "viewshedError": "ng_An error occured whilst creating visibility. Please ensure your observer location falls within the extent of your elevation surface.</p>__________________________________________ny",
  "validationError": "ng_<p>The visibility creation form has missing or invalid parameters, Please ensure:</p><ul><li>An observer location has been set.</li><li>The observer Field of View is not 0.</li><li>The observer height contains a valid value.</li><li>The min and max observable distances contain valid values.</li></ul>___________________________________________________________________________________________ny",
  "comfirmInputNotation": "ng_Confirm Input Notation________ny",
  "notationsMatch": "ng_notations match your input please confirm which you would like to use______________________ny:",
  "createBtn": "ng_Create___ny",
  "clearBtn": "ng_Clear___ny",
  "setCoordFormat": "ng_Set Coordinate Format String_________ny",
  "prefixNumbers": "ng_Add '+/-' prefix to positive and negative numbers________________ny",
  "parseCoordinatesError": "ng_Unable to parse coordinates. Please check your input_________________ny.",
  "cancelBtn": "ng_Cancel___ny",
  "applyBtn": "ng_Apply___ny",
  "DD": "ng_DD__ny",
  "DDM": "ng_DDM__ny",
  "DMS": "ng_DMS__ny",
  "DDRev": "ng_DDRev___ny",
  "DDMRev": "ng_DDMRev___ny",
  "DMSRev": "ng_DMSRev___ny",
  "USNG": "ng_USNG__ny",
  "MGRS": "ng_MGRS__ny",
  "UTM_H": "ng_UTM (H)___ny",
  "UTM": "ng_UTM__ny",
  "GARS": "ng_GARS__ny",
  "GEOREF": "ng_GEOREF___ny",
  "DDLatLongNotation": "ng_Decimal Degrees - Latitude/Longitude____________ny",
  "DDLongLatNotation": "ng_Decimal Degrees  - Longitude/Latitude____________ny",
  "DDMLatLongNotation": "ng_Degrees Decimal Minutes - Latitude/Longitude______________ny",
  "DDMLongLatNotation": "ng_Degrees Decimal Minutes - Longitude/Latitude______________ny",
  "DMSLatLongNotation": "ng_Degrees Minutes Seconds - Latitude/Longitude______________ny",
  "DMSLongLatNotation": "ng_Degrees Minutes Seconds - Longitude/Latitude______________ny",
  "GARSNotation": "ng_GARS__ny",
  "GEOREFNotation": "ng_GEOREF___ny",
  "MGRSNotation": "ng_MGRS__ny",
  "USNGNotation": "ng_USNG__ny",
  "UTMBandNotation": "ng_UTM - Band Letter______ny",
  "UTMHemNotation": "ng_UTM - Hemisphere (N/S)________ny"
});