define({
  "_widgetLabel": "ä_Visibility____Ü",
  "observerLocation": "ä_Observer Location______Ü",
  "fieldOfView": "ä_Field of View_____Ü",
  "useMilsText": "ä_Use mils for bearing angles_________Ü",
  "observerHeight": "ä_Observer Height______Ü",
  "minObsDistance": "ä_Min Observable Distance________Ü",
  "maxObsDistance": "ä_Max Observable Distance________Ü",
  "taskURLError": "ä_The widget configuration file contains a URL that is unreachable. Please check with your system administrator__________________________________Ü",
  "taskURLInvalid": "ä_The geoprocessing task configured with this widget is not valid. Please check with your system administrator_________________________________Ü",
  "viewshedError": "ä_An error occured whilst creating visibility. Please ensure your observer location falls within the extent of your elevation surface.</p>__________________________________________Ü",
  "validationError": "ä_<p>The visibility creation form has missing or invalid parameters, Please ensure:</p><ul><li>An observer location has been set.</li><li>The observer Field of View is not 0.</li><li>The observer height contains a valid value.</li><li>The min and max observable distances contain valid values.</li></ul>___________________________________________________________________________________________Ü",
  "comfirmInputNotation": "ä_Confirm Input Notation________Ü",
  "notationsMatch": "ä_notations match your input please confirm which you would like to use______________________Ü:",
  "createBtn": "ä_Create___Ü",
  "clearBtn": "ä_Clear___Ü",
  "setCoordFormat": "ä_Set Coordinate Format String_________Ü",
  "prefixNumbers": "ä_Add '+/-' prefix to positive and negative numbers________________Ü",
  "parseCoordinatesError": "ä_Unable to parse coordinates. Please check your input_________________Ü.",
  "cancelBtn": "ä_Cancel___Ü",
  "applyBtn": "ä_Apply___Ü",
  "DD": "ä_DD__Ü",
  "DDM": "ä_DDM__Ü",
  "DMS": "ä_DMS__Ü",
  "DDRev": "ä_DDRev___Ü",
  "DDMRev": "ä_DDMRev___Ü",
  "DMSRev": "ä_DMSRev___Ü",
  "USNG": "ä_USNG__Ü",
  "MGRS": "ä_MGRS__Ü",
  "UTM_H": "ä_UTM (H)___Ü",
  "UTM": "ä_UTM__Ü",
  "GARS": "ä_GARS__Ü",
  "GEOREF": "ä_GEOREF___Ü",
  "DDLatLongNotation": "ä_Decimal Degrees - Latitude/Longitude____________Ü",
  "DDLongLatNotation": "ä_Decimal Degrees  - Longitude/Latitude____________Ü",
  "DDMLatLongNotation": "ä_Degrees Decimal Minutes - Latitude/Longitude______________Ü",
  "DDMLongLatNotation": "ä_Degrees Decimal Minutes - Longitude/Latitude______________Ü",
  "DMSLatLongNotation": "ä_Degrees Minutes Seconds - Latitude/Longitude______________Ü",
  "DMSLongLatNotation": "ä_Degrees Minutes Seconds - Longitude/Latitude______________Ü",
  "GARSNotation": "ä_GARS__Ü",
  "GEOREFNotation": "ä_GEOREF___Ü",
  "MGRSNotation": "ä_MGRS__Ü",
  "USNGNotation": "ä_USNG__Ü",
  "UTMBandNotation": "ä_UTM - Band Letter______Ü",
  "UTMHemNotation": "ä_UTM - Hemisphere (N/S)________Ü"
});