define({
  "_widgetLabel": "Đ_Visibility____ớ",
  "observerLocation": "Đ_Observer Location______ớ",
  "fieldOfView": "Đ_Field of View_____ớ",
  "useMilsText": "Đ_Use mils for bearing angles_________ớ",
  "observerHeight": "Đ_Observer Height______ớ",
  "minObsDistance": "Đ_Min Observable Distance________ớ",
  "maxObsDistance": "Đ_Max Observable Distance________ớ",
  "taskURLError": "Đ_The widget configuration file contains a URL that is unreachable. Please check with your system administrator__________________________________ớ",
  "taskURLInvalid": "Đ_The geoprocessing task configured with this widget is not valid. Please check with your system administrator_________________________________ớ",
  "viewshedError": "Đ_An error occured whilst creating visibility. Please ensure your observer location falls within the extent of your elevation surface.</p>__________________________________________ớ",
  "validationError": "Đ_<p>The visibility creation form has missing or invalid parameters, Please ensure:</p><ul><li>An observer location has been set.</li><li>The observer Field of View is not 0.</li><li>The observer height contains a valid value.</li><li>The min and max observable distances contain valid values.</li></ul>___________________________________________________________________________________________ớ",
  "comfirmInputNotation": "Đ_Confirm Input Notation________ớ",
  "notationsMatch": "Đ_notations match your input please confirm which you would like to use______________________ớ:",
  "createBtn": "Đ_Create___ớ",
  "clearBtn": "Đ_Clear___ớ",
  "setCoordFormat": "Đ_Set Coordinate Format String_________ớ",
  "prefixNumbers": "Đ_Add '+/-' prefix to positive and negative numbers________________ớ",
  "parseCoordinatesError": "Đ_Unable to parse coordinates. Please check your input_________________ớ.",
  "cancelBtn": "Đ_Cancel___ớ",
  "applyBtn": "Đ_Apply___ớ",
  "DD": "Đ_DD__ớ",
  "DDM": "Đ_DDM__ớ",
  "DMS": "Đ_DMS__ớ",
  "DDRev": "Đ_DDRev___ớ",
  "DDMRev": "Đ_DDMRev___ớ",
  "DMSRev": "Đ_DMSRev___ớ",
  "USNG": "Đ_USNG__ớ",
  "MGRS": "Đ_MGRS__ớ",
  "UTM_H": "Đ_UTM (H)___ớ",
  "UTM": "Đ_UTM__ớ",
  "GARS": "Đ_GARS__ớ",
  "GEOREF": "Đ_GEOREF___ớ",
  "DDLatLongNotation": "Đ_Decimal Degrees - Latitude/Longitude____________ớ",
  "DDLongLatNotation": "Đ_Decimal Degrees  - Longitude/Latitude____________ớ",
  "DDMLatLongNotation": "Đ_Degrees Decimal Minutes - Latitude/Longitude______________ớ",
  "DDMLongLatNotation": "Đ_Degrees Decimal Minutes - Longitude/Latitude______________ớ",
  "DMSLatLongNotation": "Đ_Degrees Minutes Seconds - Latitude/Longitude______________ớ",
  "DMSLongLatNotation": "Đ_Degrees Minutes Seconds - Longitude/Latitude______________ớ",
  "GARSNotation": "Đ_GARS__ớ",
  "GEOREFNotation": "Đ_GEOREF___ớ",
  "MGRSNotation": "Đ_MGRS__ớ",
  "USNGNotation": "Đ_USNG__ớ",
  "UTMBandNotation": "Đ_UTM - Band Letter______ớ",
  "UTMHemNotation": "Đ_UTM - Hemisphere (N/S)________ớ"
});