define({
  "_widgetLabel": "ł_Visibility____ą",
  "observerLocation": "ł_Observer Location______ą",
  "fieldOfView": "ł_Field of View_____ą",
  "useMilsText": "ł_Use mils for bearing angles_________ą",
  "observerHeight": "ł_Observer Height______ą",
  "minObsDistance": "ł_Min Observable Distance________ą",
  "maxObsDistance": "ł_Max Observable Distance________ą",
  "taskURLError": "ł_The widget configuration file contains a URL that is unreachable. Please check with your system administrator__________________________________ą",
  "taskURLInvalid": "ł_The geoprocessing task configured with this widget is not valid. Please check with your system administrator_________________________________ą",
  "viewshedError": "ł_An error occured whilst creating visibility. Please ensure your observer location falls within the extent of your elevation surface.</p>__________________________________________ą",
  "validationError": "ł_<p>The visibility creation form has missing or invalid parameters, Please ensure:</p><ul><li>An observer location has been set.</li><li>The observer Field of View is not 0.</li><li>The observer height contains a valid value.</li><li>The min and max observable distances contain valid values.</li></ul>___________________________________________________________________________________________ą",
  "comfirmInputNotation": "ł_Confirm Input Notation________ą",
  "notationsMatch": "ł_notations match your input please confirm which you would like to use______________________ą:",
  "createBtn": "ł_Create___ą",
  "clearBtn": "ł_Clear___ą",
  "setCoordFormat": "ł_Set Coordinate Format String_________ą",
  "prefixNumbers": "ł_Add '+/-' prefix to positive and negative numbers________________ą",
  "parseCoordinatesError": "ł_Unable to parse coordinates. Please check your input_________________ą.",
  "cancelBtn": "ł_Cancel___ą",
  "applyBtn": "ł_Apply___ą",
  "DD": "ł_DD__ą",
  "DDM": "ł_DDM__ą",
  "DMS": "ł_DMS__ą",
  "DDRev": "ł_DDRev___ą",
  "DDMRev": "ł_DDMRev___ą",
  "DMSRev": "ł_DMSRev___ą",
  "USNG": "ł_USNG__ą",
  "MGRS": "ł_MGRS__ą",
  "UTM_H": "ł_UTM (H)___ą",
  "UTM": "ł_UTM__ą",
  "GARS": "ł_GARS__ą",
  "GEOREF": "ł_GEOREF___ą",
  "DDLatLongNotation": "ł_Decimal Degrees - Latitude/Longitude____________ą",
  "DDLongLatNotation": "ł_Decimal Degrees  - Longitude/Latitude____________ą",
  "DDMLatLongNotation": "ł_Degrees Decimal Minutes - Latitude/Longitude______________ą",
  "DDMLongLatNotation": "ł_Degrees Decimal Minutes - Longitude/Latitude______________ą",
  "DMSLatLongNotation": "ł_Degrees Minutes Seconds - Latitude/Longitude______________ą",
  "DMSLongLatNotation": "ł_Degrees Minutes Seconds - Longitude/Latitude______________ą",
  "GARSNotation": "ł_GARS__ą",
  "GEOREFNotation": "ł_GEOREF___ą",
  "MGRSNotation": "ł_MGRS__ą",
  "USNGNotation": "ł_USNG__ą",
  "UTMBandNotation": "ł_UTM - Band Letter______ą",
  "UTMHemNotation": "ł_UTM - Hemisphere (N/S)________ą"
});