define({
  "_widgetLabel": "Č_Visibility____ž",
  "observerLocation": "Č_Observer Location______ž",
  "fieldOfView": "Č_Field of View_____ž",
  "useMilsText": "Č_Use mils for bearing angles_________ž",
  "observerHeight": "Č_Observer Height______ž",
  "minObsDistance": "Č_Min Observable Distance________ž",
  "maxObsDistance": "Č_Max Observable Distance________ž",
  "taskURLError": "Č_The widget configuration file contains a URL that is unreachable. Please check with your system administrator__________________________________ž",
  "taskURLInvalid": "Č_The geoprocessing task configured with this widget is not valid. Please check with your system administrator_________________________________ž",
  "viewshedError": "Č_An error occured whilst creating visibility. Please ensure your observer location falls within the extent of your elevation surface.</p>__________________________________________ž",
  "validationError": "Č_<p>The visibility creation form has missing or invalid parameters, Please ensure:</p><ul><li>An observer location has been set.</li><li>The observer Field of View is not 0.</li><li>The observer height contains a valid value.</li><li>The min and max observable distances contain valid values.</li></ul>___________________________________________________________________________________________ž",
  "comfirmInputNotation": "Č_Confirm Input Notation________ž",
  "notationsMatch": "Č_notations match your input please confirm which you would like to use______________________ž:",
  "createBtn": "Č_Create___ž",
  "clearBtn": "Č_Clear___ž",
  "setCoordFormat": "Č_Set Coordinate Format String_________ž",
  "prefixNumbers": "Č_Add '+/-' prefix to positive and negative numbers________________ž",
  "parseCoordinatesError": "Č_Unable to parse coordinates. Please check your input_________________ž.",
  "cancelBtn": "Č_Cancel___ž",
  "applyBtn": "Č_Apply___ž",
  "DD": "Č_DD__ž",
  "DDM": "Č_DDM__ž",
  "DMS": "Č_DMS__ž",
  "DDRev": "Č_DDRev___ž",
  "DDMRev": "Č_DDMRev___ž",
  "DMSRev": "Č_DMSRev___ž",
  "USNG": "Č_USNG__ž",
  "MGRS": "Č_MGRS__ž",
  "UTM_H": "Č_UTM (H)___ž",
  "UTM": "Č_UTM__ž",
  "GARS": "Č_GARS__ž",
  "GEOREF": "Č_GEOREF___ž",
  "DDLatLongNotation": "Č_Decimal Degrees - Latitude/Longitude____________ž",
  "DDLongLatNotation": "Č_Decimal Degrees  - Longitude/Latitude____________ž",
  "DDMLatLongNotation": "Č_Degrees Decimal Minutes - Latitude/Longitude______________ž",
  "DDMLongLatNotation": "Č_Degrees Decimal Minutes - Longitude/Latitude______________ž",
  "DMSLatLongNotation": "Č_Degrees Minutes Seconds - Latitude/Longitude______________ž",
  "DMSLongLatNotation": "Č_Degrees Minutes Seconds - Longitude/Latitude______________ž",
  "GARSNotation": "Č_GARS__ž",
  "GEOREFNotation": "Č_GEOREF___ž",
  "MGRSNotation": "Č_MGRS__ž",
  "USNGNotation": "Č_USNG__ž",
  "UTMBandNotation": "Č_UTM - Band Letter______ž",
  "UTMHemNotation": "Č_UTM - Hemisphere (N/S)________ž"
});