define({
  "_widgetLabel": "須_Visibility____鷗",
  "observerLocation": "須_Observer Location______鷗",
  "fieldOfView": "須_Field of View_____鷗",
  "useMilsText": "須_Use mils for bearing angles_________鷗",
  "observerHeight": "須_Observer Height______鷗",
  "minObsDistance": "須_Min Observable Distance________鷗",
  "maxObsDistance": "須_Max Observable Distance________鷗",
  "taskURLError": "須_The widget configuration file contains a URL that is unreachable. Please check with your system administrator__________________________________鷗",
  "taskURLInvalid": "須_The geoprocessing task configured with this widget is not valid. Please check with your system administrator_________________________________鷗",
  "viewshedError": "須_An error occured whilst creating visibility. Please ensure your observer location falls within the extent of your elevation surface.</p>__________________________________________鷗",
  "validationError": "須_<p>The visibility creation form has missing or invalid parameters, Please ensure:</p><ul><li>An observer location has been set.</li><li>The observer Field of View is not 0.</li><li>The observer height contains a valid value.</li><li>The min and max observable distances contain valid values.</li></ul>___________________________________________________________________________________________鷗",
  "comfirmInputNotation": "須_Confirm Input Notation________鷗",
  "notationsMatch": "須_notations match your input please confirm which you would like to use______________________鷗:",
  "createBtn": "須_Create___鷗",
  "clearBtn": "須_Clear___鷗",
  "setCoordFormat": "須_Set Coordinate Format String_________鷗",
  "prefixNumbers": "須_Add '+/-' prefix to positive and negative numbers________________鷗",
  "parseCoordinatesError": "須_Unable to parse coordinates. Please check your input_________________鷗.",
  "cancelBtn": "須_Cancel___鷗",
  "applyBtn": "須_Apply___鷗",
  "DD": "須_DD__鷗",
  "DDM": "須_DDM__鷗",
  "DMS": "須_DMS__鷗",
  "DDRev": "須_DDRev___鷗",
  "DDMRev": "須_DDMRev___鷗",
  "DMSRev": "須_DMSRev___鷗",
  "USNG": "須_USNG__鷗",
  "MGRS": "須_MGRS__鷗",
  "UTM_H": "須_UTM (H)___鷗",
  "UTM": "須_UTM__鷗",
  "GARS": "須_GARS__鷗",
  "GEOREF": "須_GEOREF___鷗",
  "DDLatLongNotation": "須_Decimal Degrees - Latitude/Longitude____________鷗",
  "DDLongLatNotation": "須_Decimal Degrees  - Longitude/Latitude____________鷗",
  "DDMLatLongNotation": "須_Degrees Decimal Minutes - Latitude/Longitude______________鷗",
  "DDMLongLatNotation": "須_Degrees Decimal Minutes - Longitude/Latitude______________鷗",
  "DMSLatLongNotation": "須_Degrees Minutes Seconds - Latitude/Longitude______________鷗",
  "DMSLongLatNotation": "須_Degrees Minutes Seconds - Longitude/Latitude______________鷗",
  "GARSNotation": "須_GARS__鷗",
  "GEOREFNotation": "須_GEOREF___鷗",
  "MGRSNotation": "須_MGRS__鷗",
  "USNGNotation": "須_USNG__鷗",
  "UTMBandNotation": "須_UTM - Band Letter______鷗",
  "UTMHemNotation": "須_UTM - Hemisphere (N/S)________鷗"
});