//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisibilityLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisibilityLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid coordinate.
        /// </summary>
        public static string AEInvalidCoordinate {
            get {
                return ResourceManager.GetString("AEInvalidCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input.
        /// </summary>
        public static string AEInvalidInput {
            get {
                return ResourceManager.GetString("AEInvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number must be positive.
        /// </summary>
        public static string AEMustBePositive {
            get {
                return ResourceManager.GetString("AEMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number must be greater than min.
        /// </summary>
        public static string AENumMustBeGreater {
            get {
                return ResourceManager.GetString("AENumMustBeGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number must be less than max.
        /// </summary>
        public static string AENumMustBeLess {
            get {
                return ResourceManager.GetString("AENumMustBeLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number must be between {0} and {1}.
        /// </summary>
        public static string AENumRange {
            get {
                return ResourceManager.GetString("AENumRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ButtonOK {
            get {
                return ResourceManager.GetString("ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string CaptionError {
            get {
                return ResourceManager.GetString("CaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Service Layer Warning.
        /// </summary>
        public static string CaptionLayerIsImageService {
            get {
                return ResourceManager.GetString("CaptionLayerIsImageService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DD.
        /// </summary>
        public static string EnumCTDD {
            get {
                return ResourceManager.GetString("EnumCTDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDM.
        /// </summary>
        public static string EnumCTDDM {
            get {
                return ResourceManager.GetString("EnumCTDDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DMS.
        /// </summary>
        public static string EnumCTDMS {
            get {
                return ResourceManager.GetString("EnumCTDMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GARS.
        /// </summary>
        public static string EnumCTGARS {
            get {
                return ResourceManager.GetString("EnumCTGARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MGRS.
        /// </summary>
        public static string EnumCTMGRS {
            get {
                return ResourceManager.GetString("EnumCTMGRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Map Unit.
        /// </summary>
        public static string EnumCTNone {
            get {
                return ResourceManager.GetString("EnumCTNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USNG.
        /// </summary>
        public static string EnumCTUSNG {
            get {
                return ResourceManager.GetString("EnumCTUSNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTM.
        /// </summary>
        public static string EnumCTUTM {
            get {
                return ResourceManager.GetString("EnumCTUTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degrees.
        /// </summary>
        public static string EnumDegrees {
            get {
                return ResourceManager.GetString("EnumDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feet.
        /// </summary>
        public static string EnumFeet {
            get {
                return ResourceManager.GetString("EnumFeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geodesic.
        /// </summary>
        public static string EnumGeodesic {
            get {
                return ResourceManager.GetString("EnumGeodesic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grads.
        /// </summary>
        public static string EnumGrads {
            get {
                return ResourceManager.GetString("EnumGrads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great Elliptic.
        /// </summary>
        public static string EnumGreatElliptic {
            get {
                return ResourceManager.GetString("EnumGreatElliptic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometers.
        /// </summary>
        public static string EnumKilometers {
            get {
                return ResourceManager.GetString("EnumKilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loxodrome.
        /// </summary>
        public static string EnumLoxodrome {
            get {
                return ResourceManager.GetString("EnumLoxodrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meters.
        /// </summary>
        public static string EnumMeters {
            get {
                return ResourceManager.GetString("EnumMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miles.
        /// </summary>
        public static string EnumMiles {
            get {
                return ResourceManager.GetString("EnumMiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mils.
        /// </summary>
        public static string EnumMils {
            get {
                return ResourceManager.GetString("EnumMils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nautical Mile.
        /// </summary>
        public static string EnumNauticalMile {
            get {
                return ResourceManager.GetString("EnumNauticalMile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Survey Foot.
        /// </summary>
        public static string EnumSurveyFoot {
            get {
                return ResourceManager.GetString("EnumSurveyFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yards.
        /// </summary>
        public static string EnumYards {
            get {
                return ResourceManager.GetString("EnumYards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field index not found.
        /// </summary>
        public static string ExceptionFieldIndexNotFound {
            get {
                return ResourceManager.GetString("ExceptionFieldIndexNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong..
        /// </summary>
        public static string ExceptionSomethingWentWrong {
            get {
                return ResourceManager.GetString("ExceptionSomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string LabelCancel {
            get {
                return ResourceManager.GetString("LabelCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Graphics.
        /// </summary>
        public static string LabelClearGraphics {
            get {
                return ResourceManager.GetString("LabelClearGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Coordinate.
        /// </summary>
        public static string LabelDisplayCoordinate {
            get {
                return ResourceManager.GetString("LabelDisplayCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string LabelDistance {
            get {
                return ResourceManager.GetString("LabelDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field of View.
        /// </summary>
        public static string LabelFieldOfView {
            get {
                return ResourceManager.GetString("LabelFieldOfView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        public static string LabelHorizontalFOV {
            get {
                return ResourceManager.GetString("LabelHorizontalFOV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Surface.
        /// </summary>
        public static string LabelInputSurface {
            get {
                return ResourceManager.GetString("LabelInputSurface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbolize Non-Visible Data in Output.
        /// </summary>
        public static string LabelNonVisible {
            get {
                return ResourceManager.GetString("LabelNonVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observer.
        /// </summary>
        public static string LabelObserverOffset {
            get {
                return ResourceManager.GetString("LabelObserverOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observer Options.
        /// </summary>
        public static string LabelObserverOptions {
            get {
                return ResourceManager.GetString("LabelObserverOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observer Points.
        /// </summary>
        public static string LabelObserverPoints {
            get {
                return ResourceManager.GetString("LabelObserverPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height Above Surface.
        /// </summary>
        public static string LabelOffsets {
            get {
                return ResourceManager.GetString("LabelOffsets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string LabelOK {
            get {
                return ResourceManager.GetString("LabelOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string LabelSubmit {
            get {
                return ResourceManager.GetString("LabelSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface.
        /// </summary>
        public static string LabelSurfaceOffset {
            get {
                return ResourceManager.GetString("LabelSurfaceOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LLOS.
        /// </summary>
        public static string LabelTabLLOS {
            get {
                return ResourceManager.GetString("LabelTabLLOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RLOS.
        /// </summary>
        public static string LabelTabRLOS {
            get {
                return ResourceManager.GetString("LabelTabRLOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string LabelTargetOffset {
            get {
                return ResourceManager.GetString("LabelTargetOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Points.
        /// </summary>
        public static string LabelTargetPoints {
            get {
                return ResourceManager.GetString("LabelTargetPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string LabelTo {
            get {
                return ResourceManager.GetString("LabelTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        public static string LabelVerticalFOV {
            get {
                return ResourceManager.GetString("LabelVerticalFOV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LLOS_Observers.
        /// </summary>
        public static string LLOSObserversLayerName {
            get {
                return ResourceManager.GetString("LLOSObserversLayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LLOS_Output.
        /// </summary>
        public static string LLOSOutputLayerName {
            get {
                return ResourceManager.GetString("LLOSOutputLayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify that all Observer and Target Points are within the extents of the selected Surface.
        /// </summary>
        public static string LLOSPointsOutsideOfSurfaceExtent {
            get {
                return ResourceManager.GetString("LLOSPointsOutsideOfSurfaceExtent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LLOS_Sight_Lines.
        /// </summary>
        public static string LLOSSightLinesLayerName {
            get {
                return ResourceManager.GetString("LLOSSightLinesLayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LLOS_Targets.
        /// </summary>
        public static string LLOSTargetsLayerName {
            get {
                return ResourceManager.GetString("LLOSTargetsLayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected surface has not been projected.  Please project your data and try again..
        /// </summary>
        public static string LLOSUserPrompt {
            get {
                return ResourceManager.GetString("LLOSUserPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface Projection.
        /// </summary>
        public static string LLOSUserPromptCaption {
            get {
                return ResourceManager.GetString("LLOSUserPromptCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spatial Reference of Data Frame and surface must match. Please change the Spatial Reference of the Data Frame and try again..
        /// </summary>
        public static string LOSDataFrameMatch {
            get {
                return ResourceManager.GetString("LOSDataFrameMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify that the Spatial Analyst extension is available and authorized for use..
        /// </summary>
        public static string LOSSpatialAnalystLicenseInvalid {
            get {
                return ResourceManager.GetString("LOSSpatialAnalystLicenseInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spatial Reference .
        /// </summary>
        public static string LOSSpatialReferenceCaption {
            get {
                return ResourceManager.GetString("LOSSpatialReferenceCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string MenuLabelDelete {
            get {
                return ResourceManager.GetString("MenuLabelDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All.
        /// </summary>
        public static string MenuLabelDeleteAll {
            get {
                return ResourceManager.GetString("MenuLabelDeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation cancelled.
        /// </summary>
        public static string MsgCalcCancelled {
            get {
                return ResourceManager.GetString("MsgCalcCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected input surface layer is an Image Service and may take a long time to process. Do you wish to continue?.
        /// </summary>
        public static string MsgLayerIsImageService {
            get {
                return ResourceManager.GetString("MsgLayerIsImageService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point does not fall within the input extent..
        /// </summary>
        public static string MsgOutOfAOI {
            get {
                return ResourceManager.GetString("MsgOutOfAOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The surface layer was not found. Please try again..
        /// </summary>
        public static string MsgSurfaceLayerNotFound {
            get {
                return ResourceManager.GetString("MsgSurfaceLayerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results not calculated.  Check input parameters and try again..
        /// </summary>
        public static string MsgTryAgain {
            get {
                return ResourceManager.GetString("MsgTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumOfObservers.
        /// </summary>
        public static string NumOfObserversFieldName {
            get {
                return ResourceManager.GetString("NumOfObserversFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to offset.
        /// </summary>
        public static string OffsetFieldName {
            get {
                return ResourceManager.GetString("OffsetFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to offsetWithZ.
        /// </summary>
        public static string OffsetWithZFieldName {
            get {
                return ResourceManager.GetString("OffsetWithZFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RLOS_Visibility.
        /// </summary>
        public static string RLOSConvertedPolygonsLayerName {
            get {
                return ResourceManager.GetString("RLOSConvertedPolygonsLayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RLOS_Mask.
        /// </summary>
        public static string RLOSMaskLayerName {
            get {
                return ResourceManager.GetString("RLOSMaskLayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RLOS_Observers.
        /// </summary>
        public static string RLOSObserversLayerName {
            get {
                return ResourceManager.GetString("RLOSObserversLayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RLOS_Output.
        /// </summary>
        public static string RLOSOutputLayerName {
            get {
                return ResourceManager.GetString("RLOSOutputLayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify that all Observer Points are within the extents of the selected Surface.
        /// </summary>
        public static string RLOSPointsOutsideOfSurfaceExtent {
            get {
                return ResourceManager.GetString("RLOSPointsOutsideOfSurfaceExtent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected surface has not been projected.  Please project your data and try again..
        /// </summary>
        public static string RLOSUserPrompt {
            get {
                return ResourceManager.GetString("RLOSUserPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface Projection.
        /// </summary>
        public static string RLOSUserPromptCaption {
            get {
                return ResourceManager.GetString("RLOSUserPromptCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TarIsVis.
        /// </summary>
        public static string TarIsVisFieldName {
            get {
                return ResourceManager.GetString("TarIsVisFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Properties.
        /// </summary>
        public static string TitleEditProperties {
            get {
                return ResourceManager.GetString("TitleEditProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to observer.
        /// </summary>
        public static string ToolModeObserver {
            get {
                return ResourceManager.GetString("ToolModeObserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to target.
        /// </summary>
        public static string ToolModeTarget {
            get {
                return ResourceManager.GetString("ToolModeTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid vertical angle.
        /// </summary>
        public static string TooltipBottomFOVValidRange {
            get {
                return ResourceManager.GetString("TooltipBottomFOVValidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Properties.
        /// </summary>
        public static string TooltipEditProperties {
            get {
                return ResourceManager.GetString("TooltipEditProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid horizontal angle.
        /// </summary>
        public static string TooltipHFOVValidRange {
            get {
                return ResourceManager.GetString("TooltipHFOVValidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear Line of Sight.
        /// </summary>
        public static string TooltipLLOSTab {
            get {
                return ResourceManager.GetString("TooltipLLOSTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observer Map Point Tool.
        /// </summary>
        public static string TooltipMapPointTool {
            get {
                return ResourceManager.GetString("TooltipMapPointTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observer Map Point Tool.
        /// </summary>
        public static string TooltipObserverMapPointTool {
            get {
                return ResourceManager.GetString("TooltipObserverMapPointTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radial Line of Sight.
        /// </summary>
        public static string TooltipRLOSTab {
            get {
                return ResourceManager.GetString("TooltipRLOSTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Map Point Tool.
        /// </summary>
        public static string TooltipTargetMapPointTool {
            get {
                return ResourceManager.GetString("TooltipTargetMapPointTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid vertical angle.
        /// </summary>
        public static string TooltipTopFOVValidRange {
            get {
                return ResourceManager.GetString("TooltipTopFOVValidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisCode.
        /// </summary>
        public static string VisCodeFieldName {
            get {
                return ResourceManager.GetString("VisCodeFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z.
        /// </summary>
        public static string ZFieldName {
            get {
                return ResourceManager.GetString("ZFieldName", resourceCulture);
            }
        }
    }
}
