define({
  "_widgetLabel": "å_Visibility____ø",
  "observerLocation": "å_Observer Location______ø",
  "fieldOfView": "å_Field of View_____ø",
  "useMilsText": "å_Use mils for bearing angles_________ø",
  "observerHeight": "å_Observer Height______ø",
  "minObsDistance": "å_Min Observable Distance________ø",
  "maxObsDistance": "å_Max Observable Distance________ø",
  "taskURLError": "å_The widget configuration file contains a URL that is unreachable. Please check with your system administrator__________________________________ø",
  "taskURLInvalid": "å_The geoprocessing task configured with this widget is not valid. Please check with your system administrator_________________________________ø",
  "viewshedError": "å_An error occured whilst creating visibility. Please ensure your observer location falls within the extent of your elevation surface.</p>__________________________________________ø",
  "validationError": "å_<p>The visibility creation form has missing or invalid parameters, Please ensure:</p><ul><li>An observer location has been set.</li><li>The observer Field of View is not 0.</li><li>The observer height contains a valid value.</li><li>The min and max observable distances contain valid values.</li></ul>___________________________________________________________________________________________ø",
  "comfirmInputNotation": "å_Confirm Input Notation________ø",
  "notationsMatch": "å_notations match your input please confirm which you would like to use______________________ø:",
  "createBtn": "å_Create___ø",
  "clearBtn": "å_Clear___ø",
  "setCoordFormat": "å_Set Coordinate Format String_________ø",
  "prefixNumbers": "å_Add '+/-' prefix to positive and negative numbers________________ø",
  "parseCoordinatesError": "å_Unable to parse coordinates. Please check your input_________________ø.",
  "cancelBtn": "å_Cancel___ø",
  "applyBtn": "å_Apply___ø",
  "DD": "å_DD__ø",
  "DDM": "å_DDM__ø",
  "DMS": "å_DMS__ø",
  "DDRev": "å_DDRev___ø",
  "DDMRev": "å_DDMRev___ø",
  "DMSRev": "å_DMSRev___ø",
  "USNG": "å_USNG__ø",
  "MGRS": "å_MGRS__ø",
  "UTM_H": "å_UTM (H)___ø",
  "UTM": "å_UTM__ø",
  "GARS": "å_GARS__ø",
  "GEOREF": "å_GEOREF___ø",
  "DDLatLongNotation": "å_Decimal Degrees - Latitude/Longitude____________ø",
  "DDLongLatNotation": "å_Decimal Degrees  - Longitude/Latitude____________ø",
  "DDMLatLongNotation": "å_Degrees Decimal Minutes - Latitude/Longitude______________ø",
  "DDMLongLatNotation": "å_Degrees Decimal Minutes - Longitude/Latitude______________ø",
  "DMSLatLongNotation": "å_Degrees Minutes Seconds - Latitude/Longitude______________ø",
  "DMSLongLatNotation": "å_Degrees Minutes Seconds - Longitude/Latitude______________ø",
  "GARSNotation": "å_GARS__ø",
  "GEOREFNotation": "å_GEOREF___ø",
  "MGRSNotation": "å_MGRS__ø",
  "USNGNotation": "å_USNG__ø",
  "UTMBandNotation": "å_UTM - Band Letter______ø",
  "UTMHemNotation": "å_UTM - Hemisphere (N/S)________ø"
});