define({
  "_widgetLabel": "æ_Visibility____Â",
  "observerLocation": "æ_Observer Location______Â",
  "fieldOfView": "æ_Field of View_____Â",
  "useMilsText": "æ_Use mils for bearing angles_________Â",
  "observerHeight": "æ_Observer Height______Â",
  "minObsDistance": "æ_Min Observable Distance________Â",
  "maxObsDistance": "æ_Max Observable Distance________Â",
  "taskURLError": "æ_The widget configuration file contains a URL that is unreachable. Please check with your system administrator__________________________________Â",
  "taskURLInvalid": "æ_The geoprocessing task configured with this widget is not valid. Please check with your system administrator_________________________________Â",
  "viewshedError": "æ_An error occured whilst creating visibility. Please ensure your observer location falls within the extent of your elevation surface.</p>__________________________________________Â",
  "validationError": "æ_<p>The visibility creation form has missing or invalid parameters, Please ensure:</p><ul><li>An observer location has been set.</li><li>The observer Field of View is not 0.</li><li>The observer height contains a valid value.</li><li>The min and max observable distances contain valid values.</li></ul>___________________________________________________________________________________________Â",
  "comfirmInputNotation": "æ_Confirm Input Notation________Â",
  "notationsMatch": "æ_notations match your input please confirm which you would like to use______________________Â:",
  "createBtn": "æ_Create___Â",
  "clearBtn": "æ_Clear___Â",
  "setCoordFormat": "æ_Set Coordinate Format String_________Â",
  "prefixNumbers": "æ_Add '+/-' prefix to positive and negative numbers________________Â",
  "parseCoordinatesError": "æ_Unable to parse coordinates. Please check your input_________________Â.",
  "cancelBtn": "æ_Cancel___Â",
  "applyBtn": "æ_Apply___Â",
  "DD": "æ_DD__Â",
  "DDM": "æ_DDM__Â",
  "DMS": "æ_DMS__Â",
  "DDRev": "æ_DDRev___Â",
  "DDMRev": "æ_DDMRev___Â",
  "DMSRev": "æ_DMSRev___Â",
  "USNG": "æ_USNG__Â",
  "MGRS": "æ_MGRS__Â",
  "UTM_H": "æ_UTM (H)___Â",
  "UTM": "æ_UTM__Â",
  "GARS": "æ_GARS__Â",
  "GEOREF": "æ_GEOREF___Â",
  "DDLatLongNotation": "æ_Decimal Degrees - Latitude/Longitude____________Â",
  "DDLongLatNotation": "æ_Decimal Degrees  - Longitude/Latitude____________Â",
  "DDMLatLongNotation": "æ_Degrees Decimal Minutes - Latitude/Longitude______________Â",
  "DDMLongLatNotation": "æ_Degrees Decimal Minutes - Longitude/Latitude______________Â",
  "DMSLatLongNotation": "æ_Degrees Minutes Seconds - Latitude/Longitude______________Â",
  "DMSLongLatNotation": "æ_Degrees Minutes Seconds - Longitude/Latitude______________Â",
  "GARSNotation": "æ_GARS__Â",
  "GEOREFNotation": "æ_GEOREF___Â",
  "MGRSNotation": "æ_MGRS__Â",
  "USNGNotation": "æ_USNG__Â",
  "UTMBandNotation": "æ_UTM - Band Letter______Â",
  "UTMHemNotation": "æ_UTM - Hemisphere (N/S)________Â"
});