define({
  "_widgetLabel": "Į_Visibility____š",
  "observerLocation": "Į_Observer Location______š",
  "fieldOfView": "Į_Field of View_____š",
  "useMilsText": "Į_Use mils for bearing angles_________š",
  "observerHeight": "Į_Observer Height______š",
  "minObsDistance": "Į_Min Observable Distance________š",
  "maxObsDistance": "Į_Max Observable Distance________š",
  "taskURLError": "Į_The widget configuration file contains a URL that is unreachable. Please check with your system administrator__________________________________š",
  "taskURLInvalid": "Į_The geoprocessing task configured with this widget is not valid. Please check with your system administrator_________________________________š",
  "viewshedError": "Į_An error occured whilst creating visibility. Please ensure your observer location falls within the extent of your elevation surface.</p>__________________________________________š",
  "validationError": "Į_<p>The visibility creation form has missing or invalid parameters, Please ensure:</p><ul><li>An observer location has been set.</li><li>The observer Field of View is not 0.</li><li>The observer height contains a valid value.</li><li>The min and max observable distances contain valid values.</li></ul>___________________________________________________________________________________________š",
  "comfirmInputNotation": "Į_Confirm Input Notation________š",
  "notationsMatch": "Į_notations match your input please confirm which you would like to use______________________š:",
  "createBtn": "Į_Create___š",
  "clearBtn": "Į_Clear___š",
  "setCoordFormat": "Į_Set Coordinate Format String_________š",
  "prefixNumbers": "Į_Add '+/-' prefix to positive and negative numbers________________š",
  "parseCoordinatesError": "Į_Unable to parse coordinates. Please check your input_________________š.",
  "cancelBtn": "Į_Cancel___š",
  "applyBtn": "Į_Apply___š",
  "DD": "Į_DD__š",
  "DDM": "Į_DDM__š",
  "DMS": "Į_DMS__š",
  "DDRev": "Į_DDRev___š",
  "DDMRev": "Į_DDMRev___š",
  "DMSRev": "Į_DMSRev___š",
  "USNG": "Į_USNG__š",
  "MGRS": "Į_MGRS__š",
  "UTM_H": "Į_UTM (H)___š",
  "UTM": "Į_UTM__š",
  "GARS": "Į_GARS__š",
  "GEOREF": "Į_GEOREF___š",
  "DDLatLongNotation": "Į_Decimal Degrees - Latitude/Longitude____________š",
  "DDLongLatNotation": "Į_Decimal Degrees  - Longitude/Latitude____________š",
  "DDMLatLongNotation": "Į_Degrees Decimal Minutes - Latitude/Longitude______________š",
  "DDMLongLatNotation": "Į_Degrees Decimal Minutes - Longitude/Latitude______________š",
  "DMSLatLongNotation": "Į_Degrees Minutes Seconds - Latitude/Longitude______________š",
  "DMSLongLatNotation": "Į_Degrees Minutes Seconds - Longitude/Latitude______________š",
  "GARSNotation": "Į_GARS__š",
  "GEOREFNotation": "Į_GEOREF___š",
  "MGRSNotation": "Į_MGRS__š",
  "USNGNotation": "Į_USNG__š",
  "UTMBandNotation": "Į_UTM - Band Letter______š",
  "UTMHemNotation": "Į_UTM - Hemisphere (N/S)________š"
});