define({
  "_widgetLabel": "ก้_Visibility____ษฺ",
  "observerLocation": "ก้_Observer Location______ษฺ",
  "fieldOfView": "ก้_Field of View_____ษฺ",
  "useMilsText": "ก้_Use mils for bearing angles_________ษฺ",
  "observerHeight": "ก้_Observer Height______ษฺ",
  "minObsDistance": "ก้_Min Observable Distance________ษฺ",
  "maxObsDistance": "ก้_Max Observable Distance________ษฺ",
  "taskURLError": "ก้_The widget configuration file contains a URL that is unreachable. Please check with your system administrator__________________________________ษฺ",
  "taskURLInvalid": "ก้_The geoprocessing task configured with this widget is not valid. Please check with your system administrator_________________________________ษฺ",
  "viewshedError": "ก้_An error occured whilst creating visibility. Please ensure your observer location falls within the extent of your elevation surface.</p>__________________________________________ษฺ",
  "validationError": "ก้_<p>The visibility creation form has missing or invalid parameters, Please ensure:</p><ul><li>An observer location has been set.</li><li>The observer Field of View is not 0.</li><li>The observer height contains a valid value.</li><li>The min and max observable distances contain valid values.</li></ul>___________________________________________________________________________________________ษฺ",
  "comfirmInputNotation": "ก้_Confirm Input Notation________ษฺ",
  "notationsMatch": "ก้_notations match your input please confirm which you would like to use______________________ษฺ:",
  "createBtn": "ก้_Create___ษฺ",
  "clearBtn": "ก้_Clear___ษฺ",
  "setCoordFormat": "ก้_Set Coordinate Format String_________ษฺ",
  "prefixNumbers": "ก้_Add '+/-' prefix to positive and negative numbers________________ษฺ",
  "parseCoordinatesError": "ก้_Unable to parse coordinates. Please check your input_________________ษฺ.",
  "cancelBtn": "ก้_Cancel___ษฺ",
  "applyBtn": "ก้_Apply___ษฺ",
  "DD": "ก้_DD__ษฺ",
  "DDM": "ก้_DDM__ษฺ",
  "DMS": "ก้_DMS__ษฺ",
  "DDRev": "ก้_DDRev___ษฺ",
  "DDMRev": "ก้_DDMRev___ษฺ",
  "DMSRev": "ก้_DMSRev___ษฺ",
  "USNG": "ก้_USNG__ษฺ",
  "MGRS": "ก้_MGRS__ษฺ",
  "UTM_H": "ก้_UTM (H)___ษฺ",
  "UTM": "ก้_UTM__ษฺ",
  "GARS": "ก้_GARS__ษฺ",
  "GEOREF": "ก้_GEOREF___ษฺ",
  "DDLatLongNotation": "ก้_Decimal Degrees - Latitude/Longitude____________ษฺ",
  "DDLongLatNotation": "ก้_Decimal Degrees  - Longitude/Latitude____________ษฺ",
  "DDMLatLongNotation": "ก้_Degrees Decimal Minutes - Latitude/Longitude______________ษฺ",
  "DDMLongLatNotation": "ก้_Degrees Decimal Minutes - Longitude/Latitude______________ษฺ",
  "DMSLatLongNotation": "ก้_Degrees Minutes Seconds - Latitude/Longitude______________ษฺ",
  "DMSLongLatNotation": "ก้_Degrees Minutes Seconds - Longitude/Latitude______________ษฺ",
  "GARSNotation": "ก้_GARS__ษฺ",
  "GEOREFNotation": "ก้_GEOREF___ษฺ",
  "MGRSNotation": "ก้_MGRS__ษฺ",
  "USNGNotation": "ก้_USNG__ษฺ",
  "UTMBandNotation": "ก้_UTM - Band Letter______ษฺ",
  "UTMHemNotation": "ก้_UTM - Hemisphere (N/S)________ษฺ"
});