define({
  "_widgetLabel": "á_Visibility____Ó",
  "observerLocation": "á_Observer Location______Ó",
  "fieldOfView": "á_Field of View_____Ó",
  "useMilsText": "á_Use mils for bearing angles_________Ó",
  "observerHeight": "á_Observer Height______Ó",
  "minObsDistance": "á_Min Observable Distance________Ó",
  "maxObsDistance": "á_Max Observable Distance________Ó",
  "taskURLError": "á_The widget configuration file contains a URL that is unreachable. Please check with your system administrator__________________________________Ó",
  "taskURLInvalid": "á_The geoprocessing task configured with this widget is not valid. Please check with your system administrator_________________________________Ó",
  "viewshedError": "á_An error occured whilst creating visibility. Please ensure your observer location falls within the extent of your elevation surface.</p>__________________________________________Ó",
  "validationError": "á_<p>The visibility creation form has missing or invalid parameters, Please ensure:</p><ul><li>An observer location has been set.</li><li>The observer Field of View is not 0.</li><li>The observer height contains a valid value.</li><li>The min and max observable distances contain valid values.</li></ul>___________________________________________________________________________________________Ó",
  "comfirmInputNotation": "á_Confirm Input Notation________Ó",
  "notationsMatch": "á_notations match your input please confirm which you would like to use______________________Ó:",
  "createBtn": "á_Create___Ó",
  "clearBtn": "á_Clear___Ó",
  "setCoordFormat": "á_Set Coordinate Format String_________Ó",
  "prefixNumbers": "á_Add '+/-' prefix to positive and negative numbers________________Ó",
  "parseCoordinatesError": "á_Unable to parse coordinates. Please check your input_________________Ó.",
  "cancelBtn": "á_Cancel___Ó",
  "applyBtn": "á_Apply___Ó",
  "DD": "á_DD__Ó",
  "DDM": "á_DDM__Ó",
  "DMS": "á_DMS__Ó",
  "DDRev": "á_DDRev___Ó",
  "DDMRev": "á_DDMRev___Ó",
  "DMSRev": "á_DMSRev___Ó",
  "USNG": "á_USNG__Ó",
  "MGRS": "á_MGRS__Ó",
  "UTM_H": "á_UTM (H)___Ó",
  "UTM": "á_UTM__Ó",
  "GARS": "á_GARS__Ó",
  "GEOREF": "á_GEOREF___Ó",
  "DDLatLongNotation": "á_Decimal Degrees - Latitude/Longitude____________Ó",
  "DDLongLatNotation": "á_Decimal Degrees  - Longitude/Latitude____________Ó",
  "DDMLatLongNotation": "á_Degrees Decimal Minutes - Latitude/Longitude______________Ó",
  "DDMLongLatNotation": "á_Degrees Decimal Minutes - Longitude/Latitude______________Ó",
  "DMSLatLongNotation": "á_Degrees Minutes Seconds - Latitude/Longitude______________Ó",
  "DMSLongLatNotation": "á_Degrees Minutes Seconds - Longitude/Latitude______________Ó",
  "GARSNotation": "á_GARS__Ó",
  "GEOREFNotation": "á_GEOREF___Ó",
  "MGRSNotation": "á_MGRS__Ó",
  "USNGNotation": "á_USNG__Ó",
  "UTMBandNotation": "á_UTM - Band Letter______Ó",
  "UTMHemNotation": "á_UTM - Hemisphere (N/S)________Ó"
});