define({
  "_widgetLabel": "بيت_Visibility____لاحقة",
  "observerLocation": "بيت_Observer Location______لاحقة",
  "fieldOfView": "بيت_Field of View_____لاحقة",
  "useMilsText": "بيت_Use mils for bearing angles_________لاحقة",
  "observerHeight": "بيت_Observer Height______لاحقة",
  "minObsDistance": "بيت_Min Observable Distance________لاحقة",
  "maxObsDistance": "بيت_Max Observable Distance________لاحقة",
  "taskURLError": "بيت_The widget configuration file contains a URL that is unreachable. Please check with your system administrator__________________________________لاحقة",
  "taskURLInvalid": "بيت_The geoprocessing task configured with this widget is not valid. Please check with your system administrator_________________________________لاحقة",
  "viewshedError": "بيت_An error occured whilst creating visibility. Please ensure your observer location falls within the extent of your elevation surface.</p>__________________________________________لاحقة",
  "validationError": "بيت_<p>The visibility creation form has missing or invalid parameters, Please ensure:</p><ul><li>An observer location has been set.</li><li>The observer Field of View is not 0.</li><li>The observer height contains a valid value.</li><li>The min and max observable distances contain valid values.</li></ul>___________________________________________________________________________________________لاحقة",
  "comfirmInputNotation": "بيت_Confirm Input Notation________لاحقة",
  "notationsMatch": "بيت_notations match your input please confirm which you would like to use______________________لاحقة:",
  "createBtn": "بيت_Create___لاحقة",
  "clearBtn": "بيت_Clear___لاحقة",
  "setCoordFormat": "بيت_Set Coordinate Format String_________لاحقة",
  "prefixNumbers": "بيت_Add '+/-' prefix to positive and negative numbers________________لاحقة",
  "parseCoordinatesError": "بيت_Unable to parse coordinates. Please check your input_________________لاحقة.",
  "cancelBtn": "بيت_Cancel___لاحقة",
  "applyBtn": "بيت_Apply___لاحقة",
  "DD": "بيت_DD__لاحقة",
  "DDM": "بيت_DDM__لاحقة",
  "DMS": "بيت_DMS__لاحقة",
  "DDRev": "بيت_DDRev___لاحقة",
  "DDMRev": "بيت_DDMRev___لاحقة",
  "DMSRev": "بيت_DMSRev___لاحقة",
  "USNG": "بيت_USNG__لاحقة",
  "MGRS": "بيت_MGRS__لاحقة",
  "UTM_H": "بيت_UTM (H)___لاحقة",
  "UTM": "بيت_UTM__لاحقة",
  "GARS": "بيت_GARS__لاحقة",
  "GEOREF": "بيت_GEOREF___لاحقة",
  "DDLatLongNotation": "بيت_Decimal Degrees - Latitude/Longitude____________لاحقة",
  "DDLongLatNotation": "بيت_Decimal Degrees  - Longitude/Latitude____________لاحقة",
  "DDMLatLongNotation": "بيت_Degrees Decimal Minutes - Latitude/Longitude______________لاحقة",
  "DDMLongLatNotation": "بيت_Degrees Decimal Minutes - Longitude/Latitude______________لاحقة",
  "DMSLatLongNotation": "بيت_Degrees Minutes Seconds - Latitude/Longitude______________لاحقة",
  "DMSLongLatNotation": "بيت_Degrees Minutes Seconds - Longitude/Latitude______________لاحقة",
  "GARSNotation": "بيت_GARS__لاحقة",
  "GEOREFNotation": "بيت_GEOREF___لاحقة",
  "MGRSNotation": "بيت_MGRS__لاحقة",
  "USNGNotation": "بيت_USNG__لاحقة",
  "UTMBandNotation": "بيت_UTM - Band Letter______لاحقة",
  "UTMHemNotation": "بيت_UTM - Hemisphere (N/S)________لاحقة"
});