define({
  "_widgetLabel": "Ă_Visibility____ș",
  "observerLocation": "Ă_Observer Location______ș",
  "fieldOfView": "Ă_Field of View_____ș",
  "useMilsText": "Ă_Use mils for bearing angles_________ș",
  "observerHeight": "Ă_Observer Height______ș",
  "minObsDistance": "Ă_Min Observable Distance________ș",
  "maxObsDistance": "Ă_Max Observable Distance________ș",
  "taskURLError": "Ă_The widget configuration file contains a URL that is unreachable. Please check with your system administrator__________________________________ș",
  "taskURLInvalid": "Ă_The geoprocessing task configured with this widget is not valid. Please check with your system administrator_________________________________ș",
  "viewshedError": "Ă_An error occured whilst creating visibility. Please ensure your observer location falls within the extent of your elevation surface.</p>__________________________________________ș",
  "validationError": "Ă_<p>The visibility creation form has missing or invalid parameters, Please ensure:</p><ul><li>An observer location has been set.</li><li>The observer Field of View is not 0.</li><li>The observer height contains a valid value.</li><li>The min and max observable distances contain valid values.</li></ul>___________________________________________________________________________________________ș",
  "comfirmInputNotation": "Ă_Confirm Input Notation________ș",
  "notationsMatch": "Ă_notations match your input please confirm which you would like to use______________________ș:",
  "createBtn": "Ă_Create___ș",
  "clearBtn": "Ă_Clear___ș",
  "setCoordFormat": "Ă_Set Coordinate Format String_________ș",
  "prefixNumbers": "Ă_Add '+/-' prefix to positive and negative numbers________________ș",
  "parseCoordinatesError": "Ă_Unable to parse coordinates. Please check your input_________________ș.",
  "cancelBtn": "Ă_Cancel___ș",
  "applyBtn": "Ă_Apply___ș",
  "DD": "Ă_DD__ș",
  "DDM": "Ă_DDM__ș",
  "DMS": "Ă_DMS__ș",
  "DDRev": "Ă_DDRev___ș",
  "DDMRev": "Ă_DDMRev___ș",
  "DMSRev": "Ă_DMSRev___ș",
  "USNG": "Ă_USNG__ș",
  "MGRS": "Ă_MGRS__ș",
  "UTM_H": "Ă_UTM (H)___ș",
  "UTM": "Ă_UTM__ș",
  "GARS": "Ă_GARS__ș",
  "GEOREF": "Ă_GEOREF___ș",
  "DDLatLongNotation": "Ă_Decimal Degrees - Latitude/Longitude____________ș",
  "DDLongLatNotation": "Ă_Decimal Degrees  - Longitude/Latitude____________ș",
  "DDMLatLongNotation": "Ă_Degrees Decimal Minutes - Latitude/Longitude______________ș",
  "DDMLongLatNotation": "Ă_Degrees Decimal Minutes - Longitude/Latitude______________ș",
  "DMSLatLongNotation": "Ă_Degrees Minutes Seconds - Latitude/Longitude______________ș",
  "DMSLongLatNotation": "Ă_Degrees Minutes Seconds - Longitude/Latitude______________ș",
  "GARSNotation": "Ă_GARS__ș",
  "GEOREFNotation": "Ă_GEOREF___ș",
  "MGRSNotation": "Ă_MGRS__ș",
  "USNGNotation": "Ă_USNG__ș",
  "UTMBandNotation": "Ă_UTM - Band Letter______ș",
  "UTMHemNotation": "Ă_UTM - Hemisphere (N/S)________ș"
});