define({
  "_widgetLabel": "试_Visibility____验",
  "observerLocation": "试_Observer Location______验",
  "fieldOfView": "试_Field of View_____验",
  "useMilsText": "试_Use mils for bearing angles_________验",
  "observerHeight": "试_Observer Height______验",
  "minObsDistance": "试_Min Observable Distance________验",
  "maxObsDistance": "试_Max Observable Distance________验",
  "taskURLError": "试_The widget configuration file contains a URL that is unreachable. Please check with your system administrator__________________________________验",
  "taskURLInvalid": "试_The geoprocessing task configured with this widget is not valid. Please check with your system administrator_________________________________验",
  "viewshedError": "试_An error occured whilst creating visibility. Please ensure your observer location falls within the extent of your elevation surface.</p>__________________________________________验",
  "validationError": "试_<p>The visibility creation form has missing or invalid parameters, Please ensure:</p><ul><li>An observer location has been set.</li><li>The observer Field of View is not 0.</li><li>The observer height contains a valid value.</li><li>The min and max observable distances contain valid values.</li></ul>___________________________________________________________________________________________验",
  "comfirmInputNotation": "试_Confirm Input Notation________验",
  "notationsMatch": "试_notations match your input please confirm which you would like to use______________________验:",
  "createBtn": "试_Create___验",
  "clearBtn": "试_Clear___验",
  "setCoordFormat": "试_Set Coordinate Format String_________验",
  "prefixNumbers": "试_Add '+/-' prefix to positive and negative numbers________________验",
  "parseCoordinatesError": "试_Unable to parse coordinates. Please check your input_________________验.",
  "cancelBtn": "试_Cancel___验",
  "applyBtn": "试_Apply___验",
  "DD": "试_DD__验",
  "DDM": "试_DDM__验",
  "DMS": "试_DMS__验",
  "DDRev": "试_DDRev___验",
  "DDMRev": "试_DDMRev___验",
  "DMSRev": "试_DMSRev___验",
  "USNG": "试_USNG__验",
  "MGRS": "试_MGRS__验",
  "UTM_H": "试_UTM (H)___验",
  "UTM": "试_UTM__验",
  "GARS": "试_GARS__验",
  "GEOREF": "试_GEOREF___验",
  "DDLatLongNotation": "试_Decimal Degrees - Latitude/Longitude____________验",
  "DDLongLatNotation": "试_Decimal Degrees  - Longitude/Latitude____________验",
  "DDMLatLongNotation": "试_Degrees Decimal Minutes - Latitude/Longitude______________验",
  "DDMLongLatNotation": "试_Degrees Decimal Minutes - Longitude/Latitude______________验",
  "DMSLatLongNotation": "试_Degrees Minutes Seconds - Latitude/Longitude______________验",
  "DMSLongLatNotation": "试_Degrees Minutes Seconds - Longitude/Latitude______________验",
  "GARSNotation": "试_GARS__验",
  "GEOREFNotation": "试_GEOREF___验",
  "MGRSNotation": "试_MGRS__验",
  "USNGNotation": "试_USNG__验",
  "UTMBandNotation": "试_UTM - Band Letter______验",
  "UTMHemNotation": "试_UTM - Hemisphere (N/S)________验"
});