define({
  "_widgetLabel": "ķ_Visibility____ū",
  "observerLocation": "ķ_Observer Location______ū",
  "fieldOfView": "ķ_Field of View_____ū",
  "useMilsText": "ķ_Use mils for bearing angles_________ū",
  "observerHeight": "ķ_Observer Height______ū",
  "minObsDistance": "ķ_Min Observable Distance________ū",
  "maxObsDistance": "ķ_Max Observable Distance________ū",
  "taskURLError": "ķ_The widget configuration file contains a URL that is unreachable. Please check with your system administrator__________________________________ū",
  "taskURLInvalid": "ķ_The geoprocessing task configured with this widget is not valid. Please check with your system administrator_________________________________ū",
  "viewshedError": "ķ_An error occured whilst creating visibility. Please ensure your observer location falls within the extent of your elevation surface.</p>__________________________________________ū",
  "validationError": "ķ_<p>The visibility creation form has missing or invalid parameters, Please ensure:</p><ul><li>An observer location has been set.</li><li>The observer Field of View is not 0.</li><li>The observer height contains a valid value.</li><li>The min and max observable distances contain valid values.</li></ul>___________________________________________________________________________________________ū",
  "comfirmInputNotation": "ķ_Confirm Input Notation________ū",
  "notationsMatch": "ķ_notations match your input please confirm which you would like to use______________________ū:",
  "createBtn": "ķ_Create___ū",
  "clearBtn": "ķ_Clear___ū",
  "setCoordFormat": "ķ_Set Coordinate Format String_________ū",
  "prefixNumbers": "ķ_Add '+/-' prefix to positive and negative numbers________________ū",
  "parseCoordinatesError": "ķ_Unable to parse coordinates. Please check your input_________________ū.",
  "cancelBtn": "ķ_Cancel___ū",
  "applyBtn": "ķ_Apply___ū",
  "DD": "ķ_DD__ū",
  "DDM": "ķ_DDM__ū",
  "DMS": "ķ_DMS__ū",
  "DDRev": "ķ_DDRev___ū",
  "DDMRev": "ķ_DDMRev___ū",
  "DMSRev": "ķ_DMSRev___ū",
  "USNG": "ķ_USNG__ū",
  "MGRS": "ķ_MGRS__ū",
  "UTM_H": "ķ_UTM (H)___ū",
  "UTM": "ķ_UTM__ū",
  "GARS": "ķ_GARS__ū",
  "GEOREF": "ķ_GEOREF___ū",
  "DDLatLongNotation": "ķ_Decimal Degrees - Latitude/Longitude____________ū",
  "DDLongLatNotation": "ķ_Decimal Degrees  - Longitude/Latitude____________ū",
  "DDMLatLongNotation": "ķ_Degrees Decimal Minutes - Latitude/Longitude______________ū",
  "DDMLongLatNotation": "ķ_Degrees Decimal Minutes - Longitude/Latitude______________ū",
  "DMSLatLongNotation": "ķ_Degrees Minutes Seconds - Latitude/Longitude______________ū",
  "DMSLongLatNotation": "ķ_Degrees Minutes Seconds - Longitude/Latitude______________ū",
  "GARSNotation": "ķ_GARS__ū",
  "GEOREFNotation": "ķ_GEOREF___ū",
  "MGRSNotation": "ķ_MGRS__ū",
  "USNGNotation": "ķ_USNG__ū",
  "UTMBandNotation": "ķ_UTM - Band Letter______ū",
  "UTMHemNotation": "ķ_UTM - Hemisphere (N/S)________ū"
});