//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcMapAddinVisibility.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArcMapAddinVisibility.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid coordinate.
        /// </summary>
        public static string AEInvalidCoordinate {
            get {
                return ResourceManager.GetString("AEInvalidCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input.
        /// </summary>
        public static string AEInvalidInput {
            get {
                return ResourceManager.GetString("AEInvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number must be positive.
        /// </summary>
        public static string AEMustBePositive {
            get {
                return ResourceManager.GetString("AEMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feet.
        /// </summary>
        public static string EnumFeet {
            get {
                return ResourceManager.GetString("EnumFeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geodesic.
        /// </summary>
        public static string EnumGeodesic {
            get {
                return ResourceManager.GetString("EnumGeodesic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great Elliptic.
        /// </summary>
        public static string EnumGreatElliptic {
            get {
                return ResourceManager.GetString("EnumGreatElliptic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometers.
        /// </summary>
        public static string EnumKilometers {
            get {
                return ResourceManager.GetString("EnumKilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loxodrome.
        /// </summary>
        public static string EnumLoxodrome {
            get {
                return ResourceManager.GetString("EnumLoxodrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meters.
        /// </summary>
        public static string EnumMeters {
            get {
                return ResourceManager.GetString("EnumMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nautical Mile.
        /// </summary>
        public static string EnumNauticalMile {
            get {
                return ResourceManager.GetString("EnumNauticalMile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Survey Foot.
        /// </summary>
        public static string EnumSurveyFoot {
            get {
                return ResourceManager.GetString("EnumSurveyFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string LabelCancel {
            get {
                return ResourceManager.GetString("LabelCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Graphics.
        /// </summary>
        public static string LabelClearGraphics {
            get {
                return ResourceManager.GetString("LabelClearGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string LabelDistance {
            get {
                return ResourceManager.GetString("LabelDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Field of View.
        /// </summary>
        public static string LabelHorizontalFOV {
            get {
                return ResourceManager.GetString("LabelHorizontalFOV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Surface.
        /// </summary>
        public static string LabelInputSurface {
            get {
                return ResourceManager.GetString("LabelInputSurface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbolize Non-Visible Data in Output.
        /// </summary>
        public static string LabelNonVisible {
            get {
                return ResourceManager.GetString("LabelNonVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observer Offset.
        /// </summary>
        public static string LabelObserverOffset {
            get {
                return ResourceManager.GetString("LabelObserverOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observer Options.
        /// </summary>
        public static string LabelObserverOptions {
            get {
                return ResourceManager.GetString("LabelObserverOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observer Points.
        /// </summary>
        public static string LabelObserverPoints {
            get {
                return ResourceManager.GetString("LabelObserverPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string LabelOK {
            get {
                return ResourceManager.GetString("LabelOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string LabelSubmit {
            get {
                return ResourceManager.GetString("LabelSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface Offset.
        /// </summary>
        public static string LabelSurfaceOffset {
            get {
                return ResourceManager.GetString("LabelSurfaceOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LLOS.
        /// </summary>
        public static string LabelTabLLOS {
            get {
                return ResourceManager.GetString("LabelTabLLOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RLOS.
        /// </summary>
        public static string LabelTabRLOS {
            get {
                return ResourceManager.GetString("LabelTabRLOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Offset.
        /// </summary>
        public static string LabelTargetOffset {
            get {
                return ResourceManager.GetString("LabelTargetOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Points.
        /// </summary>
        public static string LabelTargetPoints {
            get {
                return ResourceManager.GetString("LabelTargetPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string LabelTo {
            get {
                return ResourceManager.GetString("LabelTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Field of View.
        /// </summary>
        public static string LabelVerticalFOV {
            get {
                return ResourceManager.GetString("LabelVerticalFOV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string MenuLabelDelete {
            get {
                return ResourceManager.GetString("MenuLabelDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All.
        /// </summary>
        public static string MenuLabelDeleteAll {
            get {
                return ResourceManager.GetString("MenuLabelDeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point does not fall within the input extent..
        /// </summary>
        public static string MsgOutOfAOI {
            get {
                return ResourceManager.GetString("MsgOutOfAOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to observer.
        /// </summary>
        public static string ToolModeObserver {
            get {
                return ResourceManager.GetString("ToolModeObserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to target.
        /// </summary>
        public static string ToolModeTarget {
            get {
                return ResourceManager.GetString("ToolModeTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Point Tool.
        /// </summary>
        public static string TooltipMapPointTool {
            get {
                return ResourceManager.GetString("TooltipMapPointTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observer Map Point Tool.
        /// </summary>
        public static string TooltipObserverMapPointTool {
            get {
                return ResourceManager.GetString("TooltipObserverMapPointTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Map Point Tool.
        /// </summary>
        public static string TooltipTargetMapPointTool {
            get {
                return ResourceManager.GetString("TooltipTargetMapPointTool", resourceCulture);
            }
        }
    }
}
