define({
  "_widgetLabel": "ã_Visibility____Ç",
  "observerLocation": "ã_Observer Location______Ç",
  "fieldOfView": "ã_Field of View_____Ç",
  "useMilsText": "ã_Use mils for bearing angles_________Ç",
  "observerHeight": "ã_Observer Height______Ç",
  "minObsDistance": "ã_Min Observable Distance________Ç",
  "maxObsDistance": "ã_Max Observable Distance________Ç",
  "taskURLError": "ã_The widget configuration file contains a URL that is unreachable. Please check with your system administrator__________________________________Ç",
  "taskURLInvalid": "ã_The geoprocessing task configured with this widget is not valid. Please check with your system administrator_________________________________Ç",
  "viewshedError": "ã_An error occured whilst creating visibility. Please ensure your observer location falls within the extent of your elevation surface.</p>__________________________________________Ç",
  "validationError": "ã_<p>The visibility creation form has missing or invalid parameters, Please ensure:</p><ul><li>An observer location has been set.</li><li>The observer Field of View is not 0.</li><li>The observer height contains a valid value.</li><li>The min and max observable distances contain valid values.</li></ul>___________________________________________________________________________________________Ç",
  "comfirmInputNotation": "ã_Confirm Input Notation________Ç",
  "notationsMatch": "ã_notations match your input please confirm which you would like to use______________________Ç:",
  "createBtn": "ã_Create___Ç",
  "clearBtn": "ã_Clear___Ç",
  "setCoordFormat": "ã_Set Coordinate Format String_________Ç",
  "prefixNumbers": "ã_Add '+/-' prefix to positive and negative numbers________________Ç",
  "parseCoordinatesError": "ã_Unable to parse coordinates. Please check your input_________________Ç.",
  "cancelBtn": "ã_Cancel___Ç",
  "applyBtn": "ã_Apply___Ç",
  "DD": "ã_DD__Ç",
  "DDM": "ã_DDM__Ç",
  "DMS": "ã_DMS__Ç",
  "DDRev": "ã_DDRev___Ç",
  "DDMRev": "ã_DDMRev___Ç",
  "DMSRev": "ã_DMSRev___Ç",
  "USNG": "ã_USNG__Ç",
  "MGRS": "ã_MGRS__Ç",
  "UTM_H": "ã_UTM (H)___Ç",
  "UTM": "ã_UTM__Ç",
  "GARS": "ã_GARS__Ç",
  "GEOREF": "ã_GEOREF___Ç",
  "DDLatLongNotation": "ã_Decimal Degrees - Latitude/Longitude____________Ç",
  "DDLongLatNotation": "ã_Decimal Degrees  - Longitude/Latitude____________Ç",
  "DDMLatLongNotation": "ã_Degrees Decimal Minutes - Latitude/Longitude______________Ç",
  "DDMLongLatNotation": "ã_Degrees Decimal Minutes - Longitude/Latitude______________Ç",
  "DMSLatLongNotation": "ã_Degrees Minutes Seconds - Latitude/Longitude______________Ç",
  "DMSLongLatNotation": "ã_Degrees Minutes Seconds - Longitude/Latitude______________Ç",
  "GARSNotation": "ã_GARS__Ç",
  "GEOREFNotation": "ã_GEOREF___Ç",
  "MGRSNotation": "ã_MGRS__Ç",
  "USNGNotation": "ã_USNG__Ç",
  "UTMBandNotation": "ã_UTM - Band Letter______Ç",
  "UTMHemNotation": "ã_UTM - Hemisphere (N/S)________Ç"
});