define({
  "_widgetLabel": "Ĳ_Visibility____ä",
  "observerLocation": "Ĳ_Observer Location______ä",
  "fieldOfView": "Ĳ_Field of View_____ä",
  "useMilsText": "Ĳ_Use mils for bearing angles_________ä",
  "observerHeight": "Ĳ_Observer Height______ä",
  "minObsDistance": "Ĳ_Min Observable Distance________ä",
  "maxObsDistance": "Ĳ_Max Observable Distance________ä",
  "taskURLError": "Ĳ_The widget configuration file contains a URL that is unreachable. Please check with your system administrator__________________________________ä",
  "taskURLInvalid": "Ĳ_The geoprocessing task configured with this widget is not valid. Please check with your system administrator_________________________________ä",
  "viewshedError": "Ĳ_An error occured whilst creating visibility. Please ensure your observer location falls within the extent of your elevation surface.</p>__________________________________________ä",
  "validationError": "Ĳ_<p>The visibility creation form has missing or invalid parameters, Please ensure:</p><ul><li>An observer location has been set.</li><li>The observer Field of View is not 0.</li><li>The observer height contains a valid value.</li><li>The min and max observable distances contain valid values.</li></ul>___________________________________________________________________________________________ä",
  "comfirmInputNotation": "Ĳ_Confirm Input Notation________ä",
  "notationsMatch": "Ĳ_notations match your input please confirm which you would like to use______________________ä:",
  "createBtn": "Ĳ_Create___ä",
  "clearBtn": "Ĳ_Clear___ä",
  "setCoordFormat": "Ĳ_Set Coordinate Format String_________ä",
  "prefixNumbers": "Ĳ_Add '+/-' prefix to positive and negative numbers________________ä",
  "parseCoordinatesError": "Ĳ_Unable to parse coordinates. Please check your input_________________ä.",
  "cancelBtn": "Ĳ_Cancel___ä",
  "applyBtn": "Ĳ_Apply___ä",
  "DD": "Ĳ_DD__ä",
  "DDM": "Ĳ_DDM__ä",
  "DMS": "Ĳ_DMS__ä",
  "DDRev": "Ĳ_DDRev___ä",
  "DDMRev": "Ĳ_DDMRev___ä",
  "DMSRev": "Ĳ_DMSRev___ä",
  "USNG": "Ĳ_USNG__ä",
  "MGRS": "Ĳ_MGRS__ä",
  "UTM_H": "Ĳ_UTM (H)___ä",
  "UTM": "Ĳ_UTM__ä",
  "GARS": "Ĳ_GARS__ä",
  "GEOREF": "Ĳ_GEOREF___ä",
  "DDLatLongNotation": "Ĳ_Decimal Degrees - Latitude/Longitude____________ä",
  "DDLongLatNotation": "Ĳ_Decimal Degrees  - Longitude/Latitude____________ä",
  "DDMLatLongNotation": "Ĳ_Degrees Decimal Minutes - Latitude/Longitude______________ä",
  "DDMLongLatNotation": "Ĳ_Degrees Decimal Minutes - Longitude/Latitude______________ä",
  "DMSLatLongNotation": "Ĳ_Degrees Minutes Seconds - Latitude/Longitude______________ä",
  "DMSLongLatNotation": "Ĳ_Degrees Minutes Seconds - Longitude/Latitude______________ä",
  "GARSNotation": "Ĳ_GARS__ä",
  "GEOREFNotation": "Ĳ_GEOREF___ä",
  "MGRSNotation": "Ĳ_MGRS__ä",
  "USNGNotation": "Ĳ_USNG__ä",
  "UTMBandNotation": "Ĳ_UTM - Band Letter______ä",
  "UTMHemNotation": "Ĳ_UTM - Hemisphere (N/S)________ä"
});