define({
  "_widgetLabel": "é_Visibility____È",
  "observerLocation": "é_Observer Location______È",
  "fieldOfView": "é_Field of View_____È",
  "useMilsText": "é_Use mils for bearing angles_________È",
  "observerHeight": "é_Observer Height______È",
  "minObsDistance": "é_Min Observable Distance________È",
  "maxObsDistance": "é_Max Observable Distance________È",
  "taskURLError": "é_The widget configuration file contains a URL that is unreachable. Please check with your system administrator__________________________________È",
  "taskURLInvalid": "é_The geoprocessing task configured with this widget is not valid. Please check with your system administrator_________________________________È",
  "viewshedError": "é_An error occured whilst creating visibility. Please ensure your observer location falls within the extent of your elevation surface.</p>__________________________________________È",
  "validationError": "é_<p>The visibility creation form has missing or invalid parameters, Please ensure:</p><ul><li>An observer location has been set.</li><li>The observer Field of View is not 0.</li><li>The observer height contains a valid value.</li><li>The min and max observable distances contain valid values.</li></ul>___________________________________________________________________________________________È",
  "comfirmInputNotation": "é_Confirm Input Notation________È",
  "notationsMatch": "é_notations match your input please confirm which you would like to use______________________È:",
  "createBtn": "é_Create___È",
  "clearBtn": "é_Clear___È",
  "setCoordFormat": "é_Set Coordinate Format String_________È",
  "prefixNumbers": "é_Add '+/-' prefix to positive and negative numbers________________È",
  "parseCoordinatesError": "é_Unable to parse coordinates. Please check your input_________________È.",
  "cancelBtn": "é_Cancel___È",
  "applyBtn": "é_Apply___È",
  "DD": "é_DD__È",
  "DDM": "é_DDM__È",
  "DMS": "é_DMS__È",
  "DDRev": "é_DDRev___È",
  "DDMRev": "é_DDMRev___È",
  "DMSRev": "é_DMSRev___È",
  "USNG": "é_USNG__È",
  "MGRS": "é_MGRS__È",
  "UTM_H": "é_UTM (H)___È",
  "UTM": "é_UTM__È",
  "GARS": "é_GARS__È",
  "GEOREF": "é_GEOREF___È",
  "DDLatLongNotation": "é_Decimal Degrees - Latitude/Longitude____________È",
  "DDLongLatNotation": "é_Decimal Degrees  - Longitude/Latitude____________È",
  "DDMLatLongNotation": "é_Degrees Decimal Minutes - Latitude/Longitude______________È",
  "DDMLongLatNotation": "é_Degrees Decimal Minutes - Longitude/Latitude______________È",
  "DMSLatLongNotation": "é_Degrees Minutes Seconds - Latitude/Longitude______________È",
  "DMSLongLatNotation": "é_Degrees Minutes Seconds - Longitude/Latitude______________È",
  "GARSNotation": "é_GARS__È",
  "GEOREFNotation": "é_GEOREF___È",
  "MGRSNotation": "é_MGRS__È",
  "USNGNotation": "é_USNG__È",
  "UTMBandNotation": "é_UTM - Band Letter______È",
  "UTMHemNotation": "é_UTM - Hemisphere (N/S)________È"
});